### ISSUE TITLE
Bot só acessa a tela dos Bosses

### ISSUE THREAD

**Issue by CorreiaDeveloper** [walterdis/lunarush-bot#1]
Olá amigo, apenas para notificar minha experiência...
O bot foi normalmente até a pagina dos bosses, porém depois disso não fez mais nada. Pelo Log vi que nao estava encontrando a imagem do Boss, então printei e substitui na pasta, e sucesso, porém nossas resoluções e outras configurações estão iguais pelo que entendi, nao sei porque ele considerou algumas imagens e outras não

**Comment by walterdis** [comment]
Opa ;)
Substituindo funcionou certinho?
Nas configurações do jogo, da de mexer na qualidade, talvez tenha algum tipo de influência também.

Se acontecer novamente, tenta colocar na qualidade mínima para ver se resolve ;)

**Comment by monte019** [comment]
Ocorreu o mesmo erro aqui!

**Comment by walterdis** [comment]
> Ocorreu o mesmo erro aqui!

Qual navegador vc usou para eu tentar replicar o erro?

**Comment by monte019** [comment]
eu substitui as imagens e coloquei o jogo em inglês e foi, duas dicas boas, fora isso o bot tá 100% completo parabéns

**Comment by CorreiaDeveloper** [comment]
> Opa ;) Substituindo funcionou certinho? Nas configurações do jogo, da de mexer na qualidade, talvez tenha algum tipo de influência também.
> 
> Se acontecer novamente, tenta colocar na qualidade mínima para ver se resolve ;)

Faz sentido viu, provavelmente deve ser o grafico, aqui eu tinha colocado tudo no full, vou tentar  com o minimo

**Comment by monte019** [comment]
Uma pergunta, depois que todos os personagens se esgotarem de energia, o que o bot faz ? fica esperando por quanto tempo até refazer o ciclo

**Comment by walterdis** [comment]
> Uma pergunta, depois que todos os personagens se esgotarem de energia, o que o bot faz ? fica esperando por quanto tempo até refazer o ciclo

É para ele voltar para a tela de seleção de estágios e aguardar por quase 2 horas (depois pretendo randomizar um pouco esse tempo).

Se quiseres modificar enquanto não faço um arquivo de configuração: 
- Abre o heroselect.py
- Linha 66 tem o método backToStageSelectAndWait()
- Modifica o sleep ali que está atualmente 7000 segundos

Vou colocar no README essa observação sobre a qualidade do jogo também ;)

**Comment by monte019** [comment]
Beleza muito obg 🙏

**Comment by walterdis** [comment]
> Beleza muito obg 🙏

Qualquer coisa da um toque, abraços ;)

**Comment by CorreiaDeveloper** [comment]
Era isso mesmo viu, o bot ta funcionando perfeitamente na resolução baixa, e com o jogo em inglês... valeu amigo <3 parabéns pelo projeto, assim que puder irei retribuir!!

**Comment by walterdis** [comment]
> Era isso mesmo viu, o bot ta funcionando perfeitamente na resolução baixa, e com o jogo em inglês... valeu amigo <3 parabéns pelo projeto, assim que puder irei retribuir!!

Valeu <3

Depois se puder, me confirma se o jogo, quando ficar aberto por muito tempo, começa a apresentar lentidão.
Se acontecer com mais pessoas além de mim, estou pensando em fazer ele recarregar o jogo de tempos em tempos também.

**Comment by CorreiaDeveloper** [comment]
> 

se aqui acontecer isso to lascado kkkkkkk como tenho trezor, nao iria acordar de madrugada pra confirmar sabe

**Comment by walterdis** [comment]
> > 
> 
> se aqui acontecer isso to lascado kkkkkkk como tenho trezor, nao iria acordar de madrugada pra confirmar sabe

No outro dia, vc vai olhar o navegador e ver que o jogo está bem lento, ai vai ter a resposta :grin:

**Comment by CorreiaDeveloper** [comment]
> > > 
> > 
> > 
> > se aqui acontecer isso to lascado kkkkkkk como tenho trezor, nao iria acordar de madrugada pra confirmar sabe
> 
> No outro dia, vc vai olhar o navegador e ver que o jogo está bem lento, ai vai ter a resposta 😁

Entao, por mim, se ele só rodar de boa, entre 1:00 e 9:00 pra mim ja ta excelente, o resto eu msm consigo fazer de boas

**Comment by monte019** [comment]
@walterdis uma dica pro bot é tentar usar randomização de movimento pra quase tudo, pq se eu não me engano já teve uma ban wave de bot, acho que adicionando isso vai ficar seguro usar, ainda fico meio atrás

**Comment by walterdis** [comment]
> @walterdis uma dica pro bot é tentar usar randomização de movimento pra quase tudo, pq se eu não me engano já teve uma ban wave de bot, acho que adicionando isso vai ficar seguro usar, ainda fico meio atrás

Já está na lista pra ser feito sim 😁 

Tem uma coisa ou outra que já está randomica mas não é tudo

**Comment by CorreiaDeveloper** [comment]
ushauhsuahu bem que vc falou, hj de manhã estava tudo em slow motion, porém fez 5 moedas na madrugada, está excelente, mt obg <3

**Comment by walterdis** [comment]
> ushauhsuahu bem que vc falou, hj de manhã estava tudo em slow motion, porém fez 5 moedas na madrugada, está excelente, mt obg <3

Poisé 😁 
Eu vou testar um esquema de recarregar o jogo de tempos em tempos pra ver se isso não acontece, se der bom, ai eu implemento e mando pro repositório.

Quero ver é como fica dentro de VM o jogo, se fora já fica lento, imagina dentro de uma 😢

**Comment by juliogabriel** [comment]
Cara, um problema que eu to tendo é o seguinte: na hora do jogo conectar a metamask pelo botao sign, ele clica na tela do jogo e a tela da metamask fica minimizada, desse jeito quando o jogo cai aqui não reconecta.

**Comment by walterdis** [comment]
> Cara, um problema que eu to tendo é o seguinte: na hora do jogo conectar a metamask pelo botao sign, ele clica na tela do jogo e a tela da metamask fica minimizada, desse jeito quando o jogo cai aqui não reconecta.

Isso acontece na primeira vez que vc vai rodar ou, é quando o bot já está rodando a algum tempo?
Qual navegador vc está usando?

**Comment by sim-lipotril** [comment]
Comecei a testar agora, volto depois para dar um feedback. Primeiramente já agradeço pela criação do bot, irá me ajudar demais. Não estava nem conseguindo dormir direito porque os ciclos estavam foda, obrigado mesmo.

**Comment by walterdis** [comment]
> Comecei a testar agora, volto depois para dar um feedback. Primeiramente já agradeço pela criação do bot, irá me ajudar demais. Não estava nem conseguindo dormir direito porque os ciclos estavam foda, obrigado mesmo.

Valeu (fiz ele pelo mesmo motivo) ;)
Se der algum problema diferente dessa issue, cria uma nova pra ficar melhor pro pessoal ver também 😁

**Comment by sim-lipotril** [comment]
Fiz o teste aqui e está acontecendo de colocar as heroinas apenas uma vez. Carregou as 3 energias e não colocou elas para matar o boss, e ficou só na tela do boss.

**Comment by walterdis** [comment]
> 

Seu game está em inglês e a configuração de qualidade está na mínima?

**Comment by sim-lipotril** [comment]
Sim, exatamente.

**Comment by sim-lipotril** [comment]
Será que pode ser por conta da resolução? Do note e 1366x768

**Comment by walterdis** [comment]
> Será que pode ser por conta da resolução? Do note e 1366x768

Bem provável que seja isso
Faz um backup das imagens no /target_images e tenta substituir por imagens que você mesmo tirou para ver se corrige.

**Comment by sim-lipotril** [comment]
Aguardar o horário de recarregarem para ver agora kk

**Comment by sim-lipotril** [comment]
Uma dúvida... Vamos supor que ele coloque as heroínas para lutarem e após isso não tem mais nenhuma carregada. Mas, nos próximos minutos teria uma nova recarga em outras. O bot ia conferir isso somente depois de 2 horas que é o horário que está la?

**Comment by walterdis** [comment]
> Uma dúvida... Vamos supor que ele coloque as heroínas para lutarem e após isso não tem mais nenhuma carregada. Mas, nos próximos minutos teria uma nova recarga em outras. O bot ia conferir isso somente depois de 2 horas que é o horário que está la?

Isso mesmo. Mais a frente, provável que eu coloque uma configuração para poder diminuir (ou podes fazer isso manualmente, aqui nessa issue se não me engano, eu explico mais acima como fazer).

Fiz dessa forma pq se não, tem chance maior do BOT mandar as bonecas separadamente e ai piora o farm
Ficar na tela de seleção delas também reparei que nem sempre a energia é atualizada corretamente

**Comment by sim-lipotril** [comment]
Isso não resolveria se você colocasse um código para ir somente quando tivesse 3 heroinas? E outra coisa... Caso tudo esteja carregado, o bot só para quando colocar todos para lutar, certo?

**Comment by sim-lipotril** [comment]
Fiz um teste aqui e tinha várias com energia carregada, mandou apenas 2.

**Comment by sim-lipotril** [comment]
![image](https://user-images.githubusercontent.com/96153507/153607242-c6045c03-7c86-4ab4-8401-93870a6558c6.png) Bug que vi agora. Mesmo com as imagens certinhas, o bot fica clicando na que está com a seta, que não tem energia.

**Comment by walterdis** [comment]
> 

Chegou a fazer a substituição das imagens que tem la no target_images? principalmente a hero-list-depleted-energy.png e a hero-list-has-energy.png

**Comment by sim-lipotril** [comment]
Sim. Mudei todas as imagens na verdade, pois estavam diferentes da resolução do meu notebook

**Comment by walterdis** [comment]
> Sim. Mudei todas as imagens na verdade, pois estavam diferentes da resolução do meu notebook

Logo que eu tiver um tempinho, vou ver se eu mudar a resolução do meu monitor para a mesma que a sua, se o erro acontece.
Enquanto isso faz outro teste: Muda a qualidade para médio e tira a screenshot ali novamente para ver se resolve.
O problema está na comparação de imagem que não está detectando a diferença de ter ou não energia

**Comment by sim-lipotril** [comment]
O erro na verdade era meu kkkk pelo que vi ele está clicando nessa imagem sem energia para rolar aonde aparece as bonecas. Como não tem mais, ele fica clicando até finalizar o ciclo

**Comment by sim-lipotril** [comment]
Por enquanto está sim. A respeito do tempo que falei. Se você adicionar algo que ele só clica em iniciar com 3 ou 2 heroinas, não resolveria?

**Comment by walterdis** [comment]
> Por enquanto está sim. A respeito do tempo que falei. Se você adicionar algo que ele só clica em iniciar com 3 ou 2 heroinas, não resolveria?

A princípio daria mais margem pra erro (da forma atual, as chances de por 3 bonecos para lutar são maiores).

Eu tenho algumas coisas que quero implementar antes (como movimento randomico do mouse, está dando uns problemas aqui) e poder configurar algumas coisas que deixei chumbada no código.

Depois posso dar uma analisada nisso sim ;)

**Comment by sim-lipotril** [comment]
Estou reduzindo o tempo que ele chega as energias para ver como vai se sair.

**Comment by sim-lipotril** [comment]
Caso eu queira colocar apenas 2 heroínas por vez, aonde eu modifico?

**Comment by walterdis** [comment]
> @walterdis uma dica pro bot é tentar usar randomização de movimento pra quase tudo, pq se eu não me engano já teve uma ban wave de bot, acho que adicionando isso vai ficar seguro usar, ainda fico meio atrás

Fiz uma atualização agora que faz os movimentos do mouse serem randômicos

**Comment by monte019** [comment]
parabéns mano ficou muito bom 😊
