### ISSUE TITLE
Scroll dos bonecos

### ISSUE THREAD

**Issue by Stermik** [walterdis/lunarush-bot#10]
Fala meu camarada, aqui o bot não ta arrastando pra chegar nos bonecos que tão embaixo, como proceder?

**Comment by jujubas6** [comment]
Blz mano, o meu nao desce para os herois abaixo so usa os 6 primeiro que estao na tela ele nao desce para seleciona os que estao mais em baixo

**Comment by jujubas6** [comment]
Vou explicar melhor mano, ele funciona certinho escolhe os herois busca o boss para luta volta tira quem ta sem energia e bota outros herois, mais so esta fazendo isso no 6 herois que ficam na tela, por exemplo eu tenho 9 herois, os 6 primeiro que esta na tela ele usa certinho mais os 3 que estao escondidos em baixo (descendo o scroll) o auto click na ta dando scroll na lista entendeu??
sera que vc me ajuda a resolver por favor?

**Comment by walterdis** [comment]
> me

Cara, isso estava acontecendo hoje na minha segunda conta e quando fui ver, a qualidade do jogo tinha voltado pro "medium", na atualização dele, acho que mudou pra isso.
Verifica e se estiver no médio, coloca na qualidade mínima novamente (e o jogo tem que estar em inglês)

**Comment by walterdis** [comment]
> Vou explicar melhor mano, ele funciona certinho escolhe os herois busca o boss para luta volta tira quem ta sem energia e bota outros herois, mais so esta fazendo isso no 6 herois que ficam na tela, por exemplo eu tenho 9 herois, os 6 primeiro que esta na tela ele usa certinho mais os 3 que estao escondidos em baixo (descendo o scroll) o auto click na ta dando scroll na lista entendeu?? sera que vc me ajuda a resolver por favor?

Cara, isso estava acontecendo hoje na minha segunda conta e quando fui ver, a qualidade do jogo tinha voltado pro "medium", na atualização dele, acho que mudou pra isso.
Verifica e se estiver no médio, coloca na qualidade mínima novamente (e o jogo tem que estar em inglês)

**Comment by jujubas6** [comment]
eu consegui arruma ontem mano fui no arquivo heroi.py procurei la alterei o scrollamount e tirei outra print para identificar o scroll, resolveu meu problema. vlw mano

**Comment by walterdis** [comment]
> eu consegui arruma ontem mano fui no arquivo heroi.py procurei la alterei o scrollamount e tirei outra print para identificar o scroll, resolveu meu problema. vlw mano

maravilha ;)
