### ISSUE TITLE
final da luta.

### ISSUE THREAD

**Issue by hows45195** [walterdis/lunarush-bot#11]
Olá amigo, primeiramente quero dizer que esse teu trabalho está incrível.
cara,estou com um problema,no final da luta contra o boss, o bot fica travado na tela "tap to continue", se tu conseguir dar essa moral e me ajudar.
obrigado desde já <3

**Comment by walterdis** [comment]
> Olá amigo, primeiramente quero dizer que esse teu trabalho está incrível. cara,estou com um problema,no final da luta contra o boss, o bot fica travado na tela "tap to continue", se tu conseguir dar essa moral e me ajudar. obrigado desde já <3

Opa, obrigado ;)
- A qualidade do seu game você colocou para ser a mínima? (da de mudar nas opções do jogo)
- Resolução de 1920x1080?
- Acontece isso sempre?
- O que aparece ali no console?

**Comment by hows45195** [comment]
consegui arrumar,tive que refazer uma das imgs, valeu mano.
outra pergunta,tem como mudar o numero de herois que o bot envia pra luta? tipo mandar de 2 em 2

**Comment by walterdis** [comment]
> consegui arrumar,tive que refazer uma das imgs, valeu mano. outra pergunta,tem como mudar o numero de herois que o bot envia pra luta? tipo mandar de 2 em 2 to perguntando pq as vezes o bot não coloca o ultimo boneco pra jogar, meu monitor não é 1920x1080 mas eu refiz todas as imgs

Ele está travado pra mandar 3 sempre (a não ser que não tenham 3, é para ele mandar o que sobrou lutar).
O que eu reparei é que anda dando uns lags no jogo e mesmo quando botei boneco na mão pra lutar, teve vezes que foram apenas dois
