### ISSUE TITLE
Tem como me ajudar ?

### ISSUE THREAD

**Issue by s1k3ra** [walterdis/lunarush-bot#12]
Sempre  que eu ligo o BOT ele fica waiting ... e não mexe em nada, com meus amigos funciona e cmg não, teria como me ajudar ?
está em 1920x1080

**Comment by walterdis** [comment]
> Sempre que eu ligo o BOT ele fica waiting ... e não mexe em nada, com meus amigos funciona e cmg não, teria como me ajudar ? está em 1920x1080

Opa tudo certo?
Verifica se o seu jogo está em inglês e se a qualidade dele está na menor possível (clica lá na engrenagem e configura) ;)

**Comment by s1k3ra** [comment]
ele começou a funcionar agora, mas não tá dando scroll pra baixo na área da batalha

**Comment by walterdis** [comment]
> ele começou a funcionar agora, mas não tá dando scroll pra baixo na área da batalha

Na seleção de bonecos?
Se vc já tiver posto o jogo em inglês e mudado a qualidade dele pra mínima, experimenta tirar as fotos de novo e substituir na pasta do target_images
