### ISSUE TITLE
Esse bot ainda funciona?

### ISSUE THREAD

**Issue by legnatv** [walterdis/lunarush-bot#13]
Olá, vi ha tempo que tinham proibido bot de macro, este ainda está seguro e funcionando certinho?

**Comment by walterdis** [comment]
> Olá, vi ha tempo que tinham proibido bot de macro, este ainda está seguro e funcionando certinho?

Tenho duas contas nele e até o momento não tive problemas.
Eu implementei movimento randômico do mouse e clicks (se vc rodar, é bem perceptível)

**Comment by legnatv** [comment]
> > Olá, vi ha tempo que tinham proibido bot de macro, este ainda está seguro e funcionando certinho?
> 
> Tenho duas contas nele e até o momento não tive problemas. Eu implementei movimento randômico do mouse e clicks (se vc rodar, é bem perceptível)

Já está usando ele ha quanto tempo?
Eu uso similar no space e no bomb, porém o luna proibiu ai fico com receio de ser pego fácil a movimentação.

**Comment by walterdis** [comment]
> > > Olá, vi ha tempo que tinham proibido bot de macro, este ainda está seguro e funcionando certinho?
> > 
> > 
> > Tenho duas contas nele e até o momento não tive problemas. Eu implementei movimento randômico do mouse e clicks (se vc rodar, é bem perceptível)
> 
> Já está usando ele ha quanto tempo? Eu uso similar no space e no bomb, porém o luna proibiu ai fico com receio de ser pego fácil a movimentação. Eu consigo personalizar o tempo que coloca para batalhar?

Desde a primeira semana que o jogo lançou 😁 
Manda ele rodar e fica olhando que vais reparar no que falei da movimentação do mouse e etc.

**Comment by walterdis** [comment]
Pra personalizar o tempo, podes ir no heroselect.py, nesse método aqui vc muda o tempo do sleep

`def backToStageSelectAndWait():
    helper.clickDestinationImage('btn-back-stage-select.png')
    print(date.dateFormatted(), ' Waiting for near 2 hours...')
    sleep(7000)`

**Comment by legnatv** [comment]
> Pra personalizar o tempo, podes ir no heroselect.py, nesse método aqui vc muda o tempo do sleep
> 
> ```
> def backToStageSelectAndWait():
>     helper.clickDestinationImage('btn-back-stage-select.png')
>     print(date.dateFormatted(), ' Waiting for near 2 hours...')
>     sleep(7000)
> ```

Cara, muito obrigado viu, vou colocar para cada 1h e 40 min para elas batalharem sempre que bater 1 de energia e ficar em movimentação constante.
