### ISSUE TITLE
Me ajude por favor O bot apenas reconhece que clica no Boss hunt

### ISSUE THREAD

**Issue by TheMasterRoot** [walterdis/lunarush-bot#14]
Boa noite poderia por favor me orientar cmo devo configurar o game e fazer o bot rodar?
a unica coisa q ele faz é clicar em Boss Hunt nada mais ele faz em nenhuma tela.
nao tive problemas com outros bots como space crypto e Bomb mas infelizmente nao consegui fazer o do luna funcionar.

Ficaria eternamente agradecido pela ajuda ( claro q ajudaria com LUS ) kkk

**Comment by walterdis** [comment]
> Boa noite poderia por favor me orientar cmo devo configurar o game e fazer o bot rodar? a unica coisa q ele faz é clicar em Boss Hunt nada mais ele faz em nenhuma tela. nao tive problemas com outros bots como space crypto e Bomb mas infelizmente nao consegui fazer o do luna funcionar.
> 
> Ficaria eternamente agradecido pela ajuda ( claro q ajudaria com LUS ) kkk

Opa, tudo certo?
Verifica se teu jogo está em inglês e a qualidade dele na mínima (tem baixa, media e alta)
Veja se está em 1920x1080
Se ainda sim não estiver funcionando, tenta tirar as prints e substituir na pasta target_images ;)

Qualquer coisa avisa aqui para tentar te auxiliar mais

**Comment by TheMasterRoot** [comment]
sim as configuracoes estao corretas vou tentar renovar os prints
agradeço

**Comment by TheMasterRoot** [comment]
outra pergunta por favor. Ate quantos  herois devo ter para que o bot funcione?

**Comment by walterdis** [comment]
> outra pergunta por favor. Ate quantos herois devo ter para que o bot funcione?

15 seria o ideal, menos que isso eu imagino que ele funcione e mais do que isso até onde sei, não aparece na listagem, então não iria influenciar
