### ISSUE TITLE
VARIAS CONTAS

### ISSUE THREAD

**Issue by evertonurbanii** [walterdis/lunarush-bot#15]
Boa tarde!
Primeiramente parabens! Seu boot funciona 100%!
Estou querendo aproveitar a baixa da moeda para abrir mais contas, existe alguma previsão para implantação do Multaccount?

**Comment by walterdis** [comment]
Opa, obrigado ;)

Pretendo fazer mas, não consigo dar uma previsão no momento.

**Comment by SrDark2021** [comment]
Já ia perguntar quando poderia usar Multaccount? no seu bot maravilhoso.

**Comment by walterdis** [comment]
> Já ia perguntar quando poderia usar Multaccount? no seu bot maravilhoso.

Enviei uma atualização para multi account e os testes que fiz aqui funcionaram até então
Façam backup da sua versão antes para poder usar ela caso de algum problema ;)
