### ISSUE TITLE
Scroll para pegar todas as heroínas

### ISSUE THREAD

**Issue by gilvam** [walterdis/lunarush-bot#16]
Simplesmente pega apenas as 6 primeiras heroínas para fazer as missões.

**Comment by walterdis** [comment]
> Simplesmente pega apenas as 6 primeiras heroínas para fazer as missões.

Opa ;)
Verifica se teu jogo está em inglês e a qualidade dele na mínima (tem baixa, media e alta)
Veja se está em 1920x1080
Se ainda sim não estiver funcionando, tenta tirar as prints e substituir na pasta target_images ;)
