### ISSUE TITLE
Como fazer p/ deslogar ao finalizar um ciclo

### ISSUE THREAD

**Issue by legnatv** [walterdis/lunarush-bot#17]
Boa noite,
Eu não tenho certeza, mas acho que quando iniciei o uso do seu bot, eu editei alguma área para não deslogar ao finalizar um ciclo de fight, ou não existe essa linha de código?
A questão é, estou querendo reativa-la 'caso eu não esteja confundindo com outro bot', atualmente eu uso bot para space crypto e esse seu do luna via python e uso um via autohotkey para 6 contas no bomb, e percebi que a do space ta comendo muito uso do processador e estou querendo deixar na tela de login no luna para ver se reduz o consumo.

Alguma solução para isso?

**Comment by walterdis** [comment]
> Boa noite, Eu não tenho certeza, mas acho que quando iniciei o uso do seu bot, eu editei alguma área para não deslogar ao finalizar um ciclo de fight, ou não existe essa linha de código? A questão é, estou querendo reativa-la 'caso eu não esteja confundindo com outro bot', atualmente eu uso bot para space crypto e esse seu do luna via python e uso um via autohotkey para 6 contas no bomb, e percebi que a do space ta comendo muito uso do processador e estou querendo deixar na tela de login no luna para ver se reduz o consumo.
> 
> Alguma solução para isso?

Opa, vc pode pegar a parte q ele faz o jogo aguardar por 2 horas antes de iniciar um novo ciclo e fazer ele recarregar a página ali antes de iniciar a espera ;)

Arquivo heroselect.py na linha 76 +-
