### ISSUE TITLE
Paralelismo com o bot do bombcrypto

### ISSUE THREAD

**Issue by THEBESTSZ** [walterdis/lunarush-bot#18]
Aoba men, vc tem alguma ideia de como adicionar pra em paralelo com o bot do bombcrypto (do mpcabete)?

**Comment by walterdis** [comment]
> Aoba men, vc tem alguma ideia de como adicionar pra em paralelo com o bot do bombcrypto (do mpcabete)?

Opa ;)
Fiz uma VM para o bomb e estou usando um fork do mpcabete pra multicontas do bomb que disponibilizaram.
Fora da VM deixo o bot do luna
