### ISSUE TITLE
AFK Message error

### ISSUE THREAD

**Issue by monte019** [walterdis/lunarush-bot#19]

**Comment by monte019** [comment]
Fala man blz? agora com essa nova att, quando vc fica um tempo afk, aparece uma msg na tela dizendo pra você clicar em OK, teria como att o bot para lidar com isso? abraços

**Comment by walterdis** [comment]
> Fala man blz? agora com essa nova att, quando vc fica um tempo afk, aparece uma msg na tela dizendo pra você clicar em OK, teria como att o bot para lidar com isso? abraços

Opa tudo certo?
O bot depois de rodar, é para ir para a tela de seleção de boss, nessa tela não aparece a mensagem de AFK.
Quando apareceu aqui na outra, o bot clicou fora da tela e normalizou.

O que ocorre ai contigo?
