### ISSUE TITLE
Bot não pega todas 15 waifu

### ISSUE THREAD

**Issue by jotaper0x** [walterdis/lunarush-bot#2]
Aoba! Primeiramente gostaria de parabenizar o Walter pela criação do bot!

Alguém mais com problema com o bot não pegar todas as lutadoras? aqui só pegou as iniciais.. as demais ficaram com a energia full.

**Comment by walterdis** [comment]
Opa, obrigado ;)

Consegues me descrever o que ele fez certinho até surgir o problema?
Pegou as 3 primeiras, lutou com elas, gastou a energia delas, removeu elas da lista de selecionados e não colocou as outras?

Sua resolução está em 1920x1080?
