### ISSUE TITLE
Pretende fazer Multaccount?

### ISSUE THREAD

**Issue by legnatv** [walterdis/lunarush-bot#20]
Bom dia, você pretende fazer o multaccount?

**Comment by walterdis** [comment]
> Bom dia, você pretende fazer o multaccount?

Pretendo fazer mas, não consigo dar uma previsão no momento ;)

**Comment by walterdis** [comment]
Pronto, enviei uma atualização para multi account e os testes que fiz aqui funcionaram até então
Faça backup da sua versão antes para poder usar ela caso de algum problema ;)

**Comment by legnatv** [comment]
> Pronto, enviei uma atualização para multi account e os testes que fiz aqui funcionaram até então Faça backup da sua versão antes para poder usar ela caso de algum problema ;)

Ja vou baixar, muito obrigado pela sua dedicação.
