### ISSUE TITLE
Disconnect from server

### ISSUE THREAD

**Issue by Soulbadguy54** [walterdis/lunarush-bot#22]
Hello, thx for your bot again. I want to suggest some improvements.

1) The error "disconnected from server" occured sometimes, usually when the server restarting the bosses global timer. But bot dont try to click "ok" in this windows, it starts to click on "login via metamask" button, that is on background and inactive, so it stucks.

2) 2nd thing consist in the logging via metamask itself. After the bot clicks at this button, usually 2 things happen:
   a) The window of metamask extension in google chrome dont open by itself, there is a need to click on extension icon manually and only later click on "sign".
   b) The window open itself, but loads the data in windows for long time, so dont contain the "sign" button. In this way bot is trying to click on "logging via metamask" button again, which causes collapse or close of metamask extension windows. Then bot stucks.

If you have time to fix this i would really appreciate than. If you need screenshots or something like that, i can make it next time error occured

**Comment by walterdis** [comment]
> 1. ne

Hi ;)
I'll take a look at the first issue.

The second, maybe increasing the wait time (issue 2.b).
Go to login.py and try to increasing **timeout=10** and **timeout=8**

**Comment by Soulbadguy54** [comment]
> > 1. ne
> 
> Hi ;) I'll take a look at the first issue.
> 
> The second, maybe increasing the wait time (issue 2.b). Go to login.py and try to increasing **timeout=10** and **timeout=8**

Hello. I want to attach some screenshots to accelerate the bugfix. Looks like github dont support spoilers for image hiding :/
This screenshot shows how looks the window after maintenence or other server restarts, such as boss count refreshment.
![disconnect](https://user-images.githubusercontent.com/70856089/157840960-b813183e-40f1-4ed1-a085-9c394c031ac3.PNG)

This screenshot shows the error, which occurs in ~10 minutes after bot sleeps. Probably its new antiafk system, so the random menu navigations are required. Or simply good and unmistakable relogin.
![afk](https://user-images.githubusercontent.com/70856089/157841702-a82b9853-4888-4280-883e-56b4062a37e6.PNG)


thx for you work!

**Comment by walterdis** [comment]
> > > 1. ne
> > 
> > 
> > Hi ;) I'll take a look at the first issue.
> > The second, maybe increasing the wait time (issue 2.b). Go to login.py and try to increasing **timeout=10** and **timeout=8**
> 
> Hello. I want to attach some screenshots to accelerate the bugfix. Looks like github dont support spoilers for image hiding :/ This screenshot shows how looks the window after maintenence or other server restarts, such as boss count refreshment. ![disconnect](https://user-images.githubusercontent.com/70856089/157840960-b813183e-40f1-4ed1-a085-9c394c031ac3.PNG)
> 
> This screenshot shows the error, which occurs in ~10 minutes after bot sleeps. Probably its new antiafk system, so the random menu navigations are required. Or simply good and unmistakable relogin. ![afk](https://user-images.githubusercontent.com/70856089/157841702-a82b9853-4888-4280-883e-56b4062a37e6.PNG)
> 
> thx for you work!

Hello ;)

Have you tryed the new version with multi account support and a popup handler that i uploaded yesterday?

**Comment by leohqr** [comment]
O jogo desconectou e ficou parado naquela tela preta de carregamento, e o bot não atualizou a página, só voltou a funcionar quando eu atualizei a página manualmente.

![loading](https://user-images.githubusercontent.com/101412840/157892959-5b288b90-dcc1-4468-9b01-0f9d799db2f1.png)

**Comment by walterdis** [comment]
Sure ;)
Sure ;)
You cannot use tabs. You have to use different browsers or create profiles.
Each active browser window must be from Luna as the photo.

If you have any other window (like windows explorer) that has "Luna Rush" in the title, the bot will assume it's a game and will try to use it.

![image](https://user-images.githubusercontent.com/1938830/157971842-229407f0-09a8-44cb-bfda-0170640a17ec.png)
