### ISSUE TITLE
Usar bot para selecionar 2 personagens

### ISSUE THREAD

**Issue by SrDark2021** [walterdis/lunarush-bot#25]
Olá, queria saber se existe alguam configuração que possa ser alterada no bot para selecionar apenas 2 personagens, assim ser melhor pra mim... obs so tenho 10 personagens e 1 fica sempre de fora.

**Comment by walterdis** [comment]
> Olá, queria saber se existe alguam configuração que possa ser alterada no bot para selecionar apenas 2 personagens, assim ser melhor pra mim... obs so tenho 10 personagens e 1 fica sempre de fora.

Opa ;)
Não existe isso implementado mas testa fazer o seguinte:
- Abre o heroselect.py
- Na linha 49 (acima do pos_x = int ..., faz uma verificação da seguinte forma:

```
if(emptySlotsAmount > 2):
    emptySlotsAmount = 2
```

![image](https://user-images.githubusercontent.com/1938830/158076919-6a7d6f61-0ad3-480f-9858-00c1f0c67223.png)

**Comment by Acauan30** [comment]
Só para te agradecer pela dica, estava com o mesmo problema e resolveu o que você mandou.

**Comment by lLeonnydas** [comment]
Boa tarde! não conseguir implementar a essa rotina que você informou para pegar 2 heroinas. seria somente colar esse comando na linha 49?

**Comment by walterdis** [comment]
> Boa tarde! não conseguir implementar a essa rotina que você informou para pegar 2 heroinas. seria somente colar esse comando na linha 49?

Isso, sem substituir nenhum dos outros códigos e mantendo a identação (igual o if que tem acima)
O que ocorre ai?
