### ISSUE TITLE
Metamask Minimizando

### ISSUE THREAD

**Issue by harinhlb** [walterdis/lunarush-bot#27]
Olá, testei a primeira versão do bot e agora o multi account, notei que as vezes o bot clica 2x no login e acaba minimzando a metamask, alguma solução pra evitar isso? Tentei no Chrome, Opera e Edge e todos tiveram o mesmo problema, mesmo que minimo, mas tem dias que ocorre com mais frequencia.

**Comment by walterdis** [comment]
> Olá, testei a primeira versão do bot e agora o multi account, notei que as vezes o bot clica 2x no login e acaba minimzando a metamask, alguma solução pra evitar isso? Tentei no Chrome, Opera e Edge e todos tiveram o mesmo problema, mesmo que minimo, mas tem dias que ocorre com mais frequencia.

Opa, chegou a reparar se a tela do metamask demora muito para abrir?
Se estiver demorando muito, experimenta aumentar o tempo de espera do bot para isso.

Abre o arquivo login.py e na linha 19 e 24, vais ver que tem um timeout=12 provavelmente
Aumenta esse tempo (em segundos) e veja se arruma ;)
