### ISSUE TITLE
Escolha de Herois

### ISSUE THREAD

**Issue by kekebr** [walterdis/lunarush-bot#29]
Uso bot somente para uma acc, com 10 herois. O bot sempre deixa 3 herois sem lutar. Como pode me ajudar amigão? Desde já agradeço!

**Comment by walterdis** [comment]
> Uso bot somente para uma acc, com 10 herois. O bot sempre deixa 3 herois sem lutar. Como pode me ajudar amigão? Desde já agradeço!

Opa.
Ele faz o scroll certinho e etc?
Consegues me dar mais informações ?

**Comment by kekebr** [comment]
Faz sim. Mas logo direto pra dar uma olhadinha sempre fica 2 ou 3 heros sem lutar com a energia full

**Comment by walterdis** [comment]
> Faz sim. Mas logo direto pra dar uma olhadinha sempre fica 2 ou 3 heros sem lutar com a energia full

E são heros de forma aleatória ou sempre os mesmos? (se forem os mesmos, quais seriam?)
Consegues me mandar print do console para ver o que ele está dizendo?
E quando você vê que isso está acontecendo, ficas observando um tempo para ver o comportamento do bot?

Como é algo que nunca aconteceu antes, preciso do máximo de detalhes possíveis pra tentar descobrir o que pode ser

**Comment by kekebr** [comment]
![Captura de Tela (20)](https://user-images.githubusercontent.com/101719259/158616811-0785e8c9-eb84-4799-9484-5e7576bbee51.png)

**Comment by kekebr** [comment]
![Captura de Tela (21)](https://user-images.githubusercontent.com/101719259/158617206-3c6164b3-10c3-48e7-b9ff-83a67bda5beb.png)
Olha ai, esses herois ele, o bot não está colocando para trabalhar

**Comment by kekebr** [comment]
São sempre os ultimos heros que não lutam

**Comment by walterdis** [comment]
> São sempre os ultimos heros que não lutam

Na última foto vi que vc deixou expandida a escolha dos heros. Sempre deixou assim?
Experimenta deixar no modo padrão, sem estar expandido

**Comment by kekebr** [comment]
Deixo ela expandida não, só expandir para mostrar os heros. Não tá fazendo scroll para baixo. Eu jogo pelo notbook pode ser isso, pela questão da resolução né? ela está 1366x768

**Comment by walterdis** [comment]
> Agora foi subistituindo a imagem, voce recomenda substitui todas imagens agora?

Cara, se começar a dar problemas você pode ir substituindo aos poucos no que precisar.
Qualquer coisa faz um backup das imagens antes também ;)
