### ISSUE TITLE
Bot não seleciona nenhum boss na tela de boss

### ISSUE THREAD

**Issue by monte019** [walterdis/lunarush-bot#3]
Fala querido td certo? seu bot foi o unico que rodou aqui kkkk tmj, mas na hora de selecionar algum boss para entrar, ele não faz nada, a setinha fica parada, tmjj

**Comment by walterdis** [comment]
> Fala querido td certo? seu bot foi o unico que rodou aqui kkkk tmj, mas na hora de selecionar algum boss para entrar, ele não faz nada, a setinha fica parada, tmjj

Opa ;)

Pelo que estou vendo, isso está acontecendo com mais pessoas. Ele não está conseguindo diferenciar o verde das outras cores.
Vai na pasta do target_images e veja como foram tiradas as fotos do boss-select-* e tira iguais e substitua lá para ver se funciona.

Antes disso, tenta mexer na qualidade do seu jogo (coloca na minima pra testar).

Se isso continuar ocorrendo, o jeito vai ser adaptar o bot para ele ir clicando em um boss por vez até entrar.

Enquanto isso vou tentar replicar o erro aqui.

**Comment by monte019** [comment]
deu certo !!!! obg mano tmj
