### ISSUE TITLE
Pega apenas heros da esquerda

### ISSUE THREAD

**Issue by PortesB** [walterdis/lunarush-bot#30]
Primeiro, valeu pelo BOT!
Está sendo selecionado apenas heros da coluna da esquerda, da direita não. Já tentei atualizar as imagens, mas segue igual...
Se puder dar uma dica, agradeço.
Valeu!

![image](https://user-images.githubusercontent.com/100965804/159166683-035ad079-b41c-4070-9be4-cbe1f6fbbb64.png)

**Comment by walterdis** [comment]
> Primeiro, valeu pelo BOT! Está sendo selecionado apenas heros da coluna da esquerda, da direita não. Já tentei atualizar as imagens, mas segue igual... Se puder dar uma dica, agradeço. Valeu!
> 
> ![image](https://user-images.githubusercontent.com/100965804/159166683-035ad079-b41c-4070-9be4-cbe1f6fbbb64.png)

Opa cara.
A qualidade do game esta na mínima? Da de mudar na configuração dele.
Verifica se resolve se vc mudar

**Comment by PortesB** [comment]
Opa, boa noite! A qualidade estava no low sim. Resolvi tirando o print novamente.

Agora tenho outra questão, não sei se prefere outra issue, mas vou te informar aqui mesmo.
Não está pegando a o último hero somente, de todas as 3 contas. Alguma ideia?

**Comment by walterdis** [comment]
> 

Estranho, aqui nunca ocorreu isso.
Testa o seguinte:
no heroselect.py no método getHeroesInListWithEnergyPositions() onde tem 
```'hero-list-depleted-energy.png', 0.9, screen)```

Experimenta diminuir um pouco, tipo 0.85 para ver se resolve (porém pode acontecer de ele tentar pegar boneco sem energia)
