### ISSUE TITLE
Duas com energia, Uma sem

### ISSUE THREAD

**Issue by piagja** [walterdis/lunarush-bot#31]
Primeiro gostaria de agradecer ao criador pelo bot, maneiro demais e tem maximizado meus lucros a rodo!
Sem palavras!

Meu problema consiste no seguinte (exemplo real): em dado momento, o bot coloca duas meninas com duas energias e uma com uma energia. Assim que a batalha acaba, ele não ta tirando a garota que ta zerada de energia e fica dando erro qaue a posição X não tem energia. Sempre!

Minha POSSÍVEL solução é, eu acho também que prefiro colocar 2 em 2 do que 3 em 3, há a função no arquivo "heroselect.py" que  possibilita isso?

Agradeço desde já e valeu pelo trabalho, ta ótimo!

**Comment by walterdis** [comment]
> Primeiro gostaria de agradecer ao criador pelo bot, maneiro demais e tem maximizado meus lucros a rodo! Sem palavras!
> 
> Meu problema consiste no seguinte (exemplo real): em dado momento, o bot coloca duas meninas com duas energias e uma com uma energia. Assim que a batalha acaba, ele não ta tirando a garota que ta zerada de energia e fica dando erro qaue a posição X não tem energia. Sempre!
> 
> Minha POSSÍVEL solução é, eu acho também que prefiro colocar 2 em 2 do que 3 em 3, há a função no arquivo "heroselect.py" que possibilita isso?
> 
> Agradeço desde já e valeu pelo trabalho, ta ótimo!

Tem um tópico aqui com uma possível solução pra isso, testa para ver se funciona e qualquer coisa me avisa ;)

Sobre não tirar: Chegou a trocar as imagens que verificam isso também?
Qualquer coisa, podes ir no método getSelectedHeroesDepletedPositions() no arquivo heroselect.py e no valor após **'hero-select-depleted-energy.png'** (aqui está 0.87), podes ir diminuindo um pouco o valor(que ai aumenta a tolerância na verificação da imagem)

**Comment by cybersecgabs** [comment]
Qual o tópico que mostra a resolução desse erro? estou tentando rodar em uma conta que possui 5 heroinas, porém o bot acaba inserindo também uma sem energia, e fica nesse loop infinito

**Comment by walterdis** [comment]
> Qual o tópico que mostra a resolução desse erro? estou tentando rodar em uma conta que possui 5 heroinas, porém o bot acaba inserindo também uma sem energia, e fica nesse loop infinito

https://github.com/walterdis/lunarush-bot/issues/25

Se o bot está inserindo uma sem energia, tira o print da imagem **hero-list-has-energy.png** e **hero-list-depleted-energy.png** novamente.

**Comment by piagja** [comment]
Aqui por parível que increça, ta corrigido.

Não fiz nada kkkk só tive de reiniciar depois de umas atts do Linux com a placa de vídeo da NVidia e daí ele parou de startar com uma guerreira sem energia.

**Comment by walterdis** [comment]
> Aqui por parível que increça, ta corrigido.
> 
> Não fiz nada kkkk só tive de reiniciar depois de umas atts do Linux com a placa de vídeo da NVidia e daí ele parou de startar com uma guerreira sem energia.

Tecnologia sendo tecnologia 😁
