### ISSUE TITLE
Executo o bot porém ele fica travado na mesma tela e não tem ação (SO Windows 10)

### ISSUE THREAD

**Issue by Andixxx1** [walterdis/lunarush-bot#32]
![image](https://user-images.githubusercontent.com/102328271/160019758-88a18a19-c8cf-49c7-99de-6b79a10b0235.png)

To tentando instalar o bot, porém ele fica travado nessa tela quando eu executo ele (Não faz nada)... O jogo já está em "low graphics", metamask e jogo já estão em Inglês tbm... Resolução da tela também já está em 1920 x1080. Sabes me dizer o porquê de não estar funcionando?

**Comment by walterdis** [comment]
> ![image](https://user-images.githubusercontent.com/102328271/160019758-88a18a19-c8cf-49c7-99de-6b79a10b0235.png)
> 
> To tentando instalar o bot, porém ele fica travado nessa tela quando eu executo ele (Não faz nada)... O jogo já está em "low graphics", metamask e jogo já estão em Inglês tbm... Resolução da tela também já está em 1920 x1080. Sabes me dizer o porquê de não estar funcionando?

Opa ;) 
No Luna, em qual tela que estava quando o bot fica dessa forma? 
Ele precisa que o jogo esteja na aba ou navegador ativo para funcionar

![image](https://user-images.githubusercontent.com/1938830/160101446-6d437c82-7ade-4d15-ab50-1129cf3665a7.png)

Se estiver tudo certo, experimenta tirar algum dos prints que estão na pasta targe_images para ver se corrige

**Comment by Andixxx1** [comment]
Bom dia,

Ele já estava ativo no navegador, trocando as imagens deu certo... Obrigado!!!

Agora a dúvida é outra, eu tenho 4 contas no LUNA, se eu abrir as 4, ele não está jogando automaticamente nas 4, ele só joga em uma... Ele joga na conta aberta, tira as energias e fica esperando 2 horas para jogar novamente na mesma conta... Como o bot foi desenvolvido para as multicontas, ele não deveria já jogar na próxima conta (achar a outra aba do navegador aberta) ao acabar a energia da conta 1? Existe alguma configuração que deve ser realizada?

A versão baixada foi a 1.1.0

**Comment by walterdis** [comment]
> Bom dia,
> 
> Ele já estava ativo no navegador, trocando as imagens deu certo... Obrigado!!!
> 
> Agora a dúvida é outra, eu tenho 4 contas no LUNA, se eu abrir as 4, ele não está jogando automaticamente nas 4, ele só joga em uma... Ele joga na conta aberta, tira as energias e fica esperando 2 horas para jogar novamente na mesma conta... Como o bot foi desenvolvido para as multicontas, ele não deveria já jogar na próxima conta (achar a outra aba do navegador aberta) ao acabar a energia da conta 1? Existe alguma configuração que deve ser realizada?
> 
> A versão baixada foi a 1.1.0

Opa ;)

O Multi contas funciona apenas para windows, para o linux não funciona e quando detecta que é esse SO, ele coloca para rodar no modo único mesmo.
Ainda não tive tempo de ver como fazer funcionar no linux (não utilizo ele)

**Comment by Andixxx1** [comment]
Boa noite,

Cara, eu estou utilizando o bot no Windows 10, fico com 4 janelas do navegador aberta (1 para cada conta), porém quando ele termina de jogar na primeira conta, o bot da a mensagem informando que ele vai ficar 2h esperando a próxima rodada... Então, tipo, em vez de nesse tempo ele partir para a próxima conta (jogar na outra aba do navegador aberta), ele fica apenas na conta 1... Então ele só joga em uma conta e não ta detectando as outras contas abertas.

Tem alguma coisa que eu estou fazendo de errado? Estou utilizando um perfil do Chrome separado (que seriam as abas do navegador aberta) para cada conta.

**Comment by walterdis** [comment]
> Boa noite,
> 
> Cara, eu estou utilizando o bot no Windows 10, fico com 4 janelas do navegador aberta (1 para cada conta), porém quando ele termina de jogar na primeira conta, o bot da a mensagem informando que ele vai ficar 2h esperando a próxima rodada... Então, tipo, em vez de nesse tempo ele partir para a próxima conta (jogar na outra aba do navegador aberta), ele fica apenas na conta 1... Então ele só joga em uma conta e não ta detectando as outras contas abertas.
> 
> Tem alguma coisa que eu estou fazendo de errado? Estou utilizando um perfil do Chrome separado (que seriam as abas do navegador aberta) para cada conta.

Opa.
Para o bot funcionar como multi account, ele tem que estar ativo na barra de tarefas do windows pq ele usa ela para detectar os nomes igual a imagem abaixo (no caso esse é do bombcrypto mas é a mesma lógica pro luna)

![image](https://user-images.githubusercontent.com/1938830/160306493-904794dc-6ddc-429f-836d-855f191a137f.png)


Obs: Estava pensando aqui agora e talvez vc esteja utilizando a versão que não tinha multi acct ainda.
Baixa a mais atual dessa forma:

![image](https://user-images.githubusercontent.com/1938830/160306568-cd7e8533-521f-4119-802b-57b0116cbba3.png)
