### ISSUE TITLE
How do we configure Fix Resting hours?

### ISSUE THREAD

**Issue by mktrilogy12** [walterdis/lunarush-bot#33]
Like we make it rest for 4 hours and it will automatically deploy Warriors after rest period? Thanks so much for this wonderful bot.

**Comment by walterdis** [comment]
> Like we make it rest for 4 hours and it will automatically deploy Warriors after rest period? Thanks so much for this wonderful bot.

Hello, thanks ;)

Open index.py and modify the waitTime variable

![image](https://user-images.githubusercontent.com/1938830/160179881-ff218f0c-413d-4b63-bd08-38cf6c5b76d0.png)

**Comment by mktrilogy12** [comment]
id did that and nothing happened. is it for linux that part as im windows?

**Comment by walterdis** [comment]
> I did that and nothing happened. is it for linux that part as im windows?
> 
> also below it should we also modify it?
> 
> this part
> 
> print('Finished all plays... waiting to begin again.') time.sleep(7200+uniform(20, 300))
> 
> same settings as the above or only the part you point out? thank you soo much for help.

Take a look at line 84, time.sleep(720 + uniform(20,300))
720 seconds = 12 minutes, you can increase there

**Comment by mktrilogy12** [comment]
> > I did that and nothing happened. is it for linux that part as im windows?
> > also below it should we also modify it?
> > this part
> > print('Finished all plays... waiting to begin again.') time.sleep(7200+uniform(20, 300))
> > same settings as the above or only the part you point out? thank you soo much for help.
> 
> Take a look at line 84, time.sleep(720 + uniform(20,300)) 720 seconds = 12 minutes, you can increase there

that did it. than you so much brother.
