### ISSUE TITLE
Waiting... Waiting...

### ISSUE THREAD

**Issue by SperFeckT** [walterdis/lunarush-bot#34]
![Screenshot_1](https://user-images.githubusercontent.com/54272882/160191976-ac8c580e-8702-42a1-ba1c-fc68f9bf11b9.png)
Hello! Can u help me to fix it? What should I do next?

**Comment by walterdis** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/54272882/160191976-ac8c580e-8702-42a1-ba1c-fc68f9bf11b9.png) Hello! Can u help me to fix it? What should I do next?

Is your game quality at the minimum? (you can change in the game config)

**Comment by SperFeckT** [comment]
> > ![Screenshot_1](https://user-images.githubusercontent.com/54272882/160191976-ac8c580e-8702-42a1-ba1c-fc68f9bf11b9.png) Hello! Can u help me to fix it? What should I do next?
> 
> Is your game quality at the minimum? (you can change in the game config)

Yep Its minimum but I solved the problem already^^ Thank u!
