### ISSUE TITLE
atualizar a imagem energia bot

### ISSUE THREAD

**Issue by Saindramar** [walterdis/lunarush-bot#36]
depois da atualização de hoje precisa atualizar para imagem nova de energia.

**Comment by Celiojrfoda** [comment]
Só atualizar a imagem da certo será? Não precisa colocar outra linha de código?

**Comment by Saindramar** [comment]
aguardando para dar a maozinha o dev.

**Comment by hznandu** [comment]
Estou disponível para ajudar, se precisar, inclusive estou fazendo uma pequena doação em BNB pelo trabalho desenvolvido. Obrigado!

**Comment by Celiojrfoda** [comment]
Se trocar os prints de sem energia por 0/3 pra tirar da batalha e o com energia confrontar 3 imagens usando o or* 1/3 2/3 3/3* pra mandar trabalhar creio que fique funcional vou alterar no código aqui pra testar

**Comment by krikmo** [comment]
Acho que se trocar o "hero-list-has-energy" pelo 1/3 novo já deve resolver temporariamente, porque dificilmente o bot deixa carregar até o 2/3 de tão rápido que é. Assim resolveria o problema de ficar tentando batalhar com 0 energias. Se alguém puder manda um print do 1/3 atual, eu ainda tenho que esperar um tempo.

**Comment by DiogoAntenor** [comment]
fala man eu tenho aqui me passa seu email que mando

**Comment by krikmo** [comment]
Dá pra mandar por aqui, só clicar na imagem e arrastar:

![hero-list-has-energy](https://user-images.githubusercontent.com/12498661/160901139-ececc783-9bcd-49c8-901b-188789009e70.png)
a

**Comment by DiogoAntenor** [comment]
top man veja se da para ver

![Captura de tela 2022-03-30 145858](https://user-images.githubusercontent.com/68443718/160901262-14ffacc7-cfc0-431a-a124-2618fd034a5b.png)
![Captura de tela 2022-03-30 145841](https://user-images.githubusercontent.com/68443718/160901278-53fddc22-a054-4a08-8bee-755362e1f450.png)

**Comment by DiogoAntenor** [comment]
o meu bot nao entendeu essas imagens ele ate encontra os bonecos porem ele clica muito para direita e nao seleciona ninguem kkkkkkkkkk

ele consegue acertar bem no meio de 2 personagens

**Comment by TarikPonciano** [comment]
> o meu bot nao entendeu essas imagens ele ate encontra os bonecos porem ele clica muito para direita e nao seleciona ninguem kkkkkkkkkk
> 
> ele consegue acertar bem no meio de 2 personagens

Também tive esse problema, mas foi só ajustar a imagem. Tenta deixar um pedacinho fora da energia aparecendo pro bot entender que aquele personagem foi ou não selecionado

![hero-list-depleted-energy](https://user-images.githubusercontent.com/40394108/160905849-ee07485b-c42f-4824-aeaf-ef1cbb3c12f3.png)
![hero-list-has-energy](https://user-images.githubusercontent.com/40394108/160905850-e3765075-b5f1-4103-a7dc-c24cb3976a25.png)
![hero-select-depleted-energy](https://user-images.githubusercontent.com/40394108/160905853-2de88361-91a6-4d7d-b7a2-45c530d088c4.png)
.

**Comment by Soulbadguy54** [comment]
Waiting for update :) Thx, bro

**Comment by krikmo** [comment]
> > o meu bot nao entendeu essas imagens ele ate encontra os bonecos porem ele clica muito para direita e nao seleciona ninguem kkkkkkkkkk
> > ele consegue acertar bem no meio de 2 personagens
> 
> Também tive esse problema, mas foi só ajustar a imagem. Tenta deixar um pedacinho fora da energia aparecendo pro bot entender que aquele personagem foi ou não selecionado
> 
> ![hero-list-depleted-energy](https://user-images.githubusercontent.com/40394108/160905849-ee07485b-c42f-4824-aeaf-ef1cbb3c12f3.png) ![hero-list-has-energy](https://user-images.githubusercontent.com/40394108/160905850-e3765075-b5f1-4103-a7dc-c24cb3976a25.png) ![hero-select-depleted-energy](https://user-images.githubusercontent.com/40394108/160905853-2de88361-91a6-4d7d-b7a2-45c530d088c4.png) .

Funcionou aqui! Pra quem tá em dúvida, substitua da seguinte forma:

![Screenshot_1](https://user-images.githubusercontent.com/12498661/160907258-c8fc5ab3-d868-4c65-bbfd-e6ba8f5958f4.png)

O bot vai falhar quando tiver mais de duas energias, mas aí a gente vê depois

**Comment by gel313** [comment]
Consegui um paliativo, ele seleciona apenas se tiver 3 ou 2 nergias. Mas depois de selecionar ele só desceleciona quando zerar a energia. E volta a selecionar com pelo menos 2. Só descompactar e substituir aí na pasta targets esses 3 prints. 
https://drive.google.com/file/d/1yHFXlzKpGhIFBI1SFvXupDH1Abcwqus_/view?usp=drivesdk

**Comment by hznandu** [comment]
> > > o meu bot nao entendeu essas imagens ele ate encontra os bonecos porem ele clica muito para direita e nao seleciona ninguem kkkkkkkkkk
> > > ele consegue acertar bem no meio de 2 personagens
> > 
> > 
> > Também tive esse problema, mas foi só ajustar a imagem. Tenta deixar um pedacinho fora da energia aparecendo pro bot entender que aquele personagem foi ou não selecionado
> > ![hero-list-depleted-energy](https://user-images.githubusercontent.com/40394108/160905849-ee07485b-c42f-4824-aeaf-ef1cbb3c12f3.png) ![hero-list-has-energy](https://user-images.githubusercontent.com/40394108/160905850-e3765075-b5f1-4103-a7dc-c24cb3976a25.png) ![hero-select-depleted-energy](https://user-images.githubusercontent.com/40394108/160905853-2de88361-91a6-4d7d-b7a2-45c530d088c4.png) .
> 
> Funcionou aqui! Pra quem tá em dúvida, substitua da seguinte forma:
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/12498661/160907258-c8fc5ab3-d868-4c65-bbfd-e6ba8f5958f4.png)
> 
> O bot vai falhar quando tiver mais de duas energias, mas aí a gente vê depois

Deu certo aqui! Estou testando.

**Comment by hznandu** [comment]
> o meu bot nao entendeu essas imagens ele ate encontra os bonecos porem ele clica muito para direita e nao seleciona ninguem kkkkkkkkkk
> 
> ele consegue acertar bem no meio de 2 personagens

Verifica se não está em qualidade baixa (low)

**Comment by Acauan30** [comment]
> > > o meu bot nao entendeu essas imagens ele ate encontra os bonecos porem ele clica muito para direita e nao seleciona ninguem kkkkkkkkkk
> > > ele consegue acertar bem no meio de 2 personagens
> > 
> > 
> > Também tive esse problema, mas foi só ajustar a imagem. Tenta deixar um pedacinho fora da energia aparecendo pro bot entender que aquele personagem foi ou não selecionado
> > ![hero-list-depleted-energy](https://user-images.githubusercontent.com/40394108/160905849-ee07485b-c42f-4824-aeaf-ef1cbb3c12f3.png) ![hero-list-has-energy](https://user-images.githubusercontent.com/40394108/160905850-e3765075-b5f1-4103-a7dc-c24cb3976a25.png) ![hero-select-depleted-energy](https://user-images.githubusercontent.com/40394108/160905853-2de88361-91a6-4d7d-b7a2-45c530d088c4.png) .
> 
> Funcionou aqui! Pra quem tá em dúvida, substitua da seguinte forma:
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/12498661/160907258-c8fc5ab3-d868-4c65-bbfd-e6ba8f5958f4.png)
> 
> O bot vai falhar quando tiver mais de duas energias, mas aí a gente vê depois

aqui não deu certo, ele fez a primeira run, bateu no boss, ai na segunda ele selecionou só um e colocou para atacar o boss

**Comment by TarikPonciano** [comment]
> > > > o meu bot nao entendeu essas imagens ele ate encontra os bonecos porem ele clica muito para direita e nao seleciona ninguem kkkkkkkkkk
> > > > ele consegue acertar bem no meio de 2 personagens
> > > 
> > > 
> > > Também tive esse problema, mas foi só ajustar a imagem. Tenta deixar um pedacinho fora da energia aparecendo pro bot entender que aquele personagem foi ou não selecionado
> > > ![hero-list-depleted-energy](https://user-images.githubusercontent.com/40394108/160905849-ee07485b-c42f-4824-aeaf-ef1cbb3c12f3.png) ![hero-list-has-energy](https://user-images.githubusercontent.com/40394108/160905850-e3765075-b5f1-4103-a7dc-c24cb3976a25.png) ![hero-select-depleted-energy](https://user-images.githubusercontent.com/40394108/160905853-2de88361-91a6-4d7d-b7a2-45c530d088c4.png) .
> > 
> > 
> > Funcionou aqui! Pra quem tá em dúvida, substitua da seguinte forma:
> > ![Screenshot_1](https://user-images.githubusercontent.com/12498661/160907258-c8fc5ab3-d868-4c65-bbfd-e6ba8f5958f4.png)
> > O bot vai falhar quando tiver mais de duas energias, mas aí a gente vê depois
> 
> aqui não deu certo, ele fez a primeira run, bateu no boss, ai na segunda ele selecionou só um e colocou para atacar o boss

O ponto que o @hznandu levantou é importante, minhas imagens foram printadas na qualidade low, se o teu jogo não estiver no low pode falhar. De toda forma tenta bater um print parecido tu mesmo se for necessário, testa com mais parte cinza aparecendo.

**Comment by Acauan30** [comment]
> > > > > o meu bot nao entendeu essas imagens ele ate encontra os bonecos porem ele clica muito para direita e nao seleciona ninguem kkkkkkkkkk
> > > > > ele consegue acertar bem no meio de 2 personagens
> > > > 
> > > > 
> > > > Também tive esse problema, mas foi só ajustar a imagem. Tenta deixar um pedacinho fora da energia aparecendo pro bot entender que aquele personagem foi ou não selecionado
> > > > ![hero-list-depleted-energy](https://user-images.githubusercontent.com/40394108/160905849-ee07485b-c42f-4824-aeaf-ef1cbb3c12f3.png) ![hero-list-has-energy](https://user-images.githubusercontent.com/40394108/160905850-e3765075-b5f1-4103-a7dc-c24cb3976a25.png) ![hero-select-depleted-energy](https://user-images.githubusercontent.com/40394108/160905853-2de88361-91a6-4d7d-b7a2-45c530d088c4.png) .
> > > 
> > > 
> > > Funcionou aqui! Pra quem tá em dúvida, substitua da seguinte forma:
> > > ![Screenshot_1](https://user-images.githubusercontent.com/12498661/160907258-c8fc5ab3-d868-4c65-bbfd-e6ba8f5958f4.png)
> > > O bot vai falhar quando tiver mais de duas energias, mas aí a gente vê depois
> > 
> > 
> > aqui não deu certo, ele fez a primeira run, bateu no boss, ai na segunda ele selecionou só um e colocou para atacar o boss
> 
> O ponto que o @hznandu levantou é importante, minhas imagens foram printadas na qualidade low, se o teu jogo não estiver no low pode falhar. De toda forma tenta bater um print parecido tu mesmo se for necessário, testa com mais parte cinza aparecendo.

eu fiz uma correção no cod para atacar de 2 em 2 ao inves de 3 em 3, vou reverter essa configuração e ve se resolve

**Comment by Brasilerinho** [comment]
> ![hero-list-depleted-energy](https://user-images.githubusercontent.com/40394108/160905849-ee07485b-c42f-4824-aeaf-ef1cbb3c12f3.png)

obg funcionou pra mim!

**Comment by walterdis** [comment]
Opa.

Já estou trabalhando para tentar resolver de alguma forma.
Já adianto que estou usando a qualidade da imagem na média e o zoom em 125% do navegador pois como é com números agora, as chances de dar problema são maiores.

A forma que estou fazendo vai ser para pegar os que tem 2 ou 3 energias, abaixo disso o bot se confunde

**Comment by walterdis** [comment]
Pronto, acabei de enviar uma atualização.

**Comment by Acauan30** [comment]
o que acontece com o bot rodando e cai a 1 energia?

**Comment by walterdis** [comment]
> o que acontece com o bot rodando e cai a 1 energia?

Se estiver selecionada pra lutar, ela vai lugar, se não, provavelmente não vai ser selecionada, somente quando tiver de 2 para cima.

**Comment by booyxlo** [comment]
> Opa.
> 
> Já estou trabalhando para tentar resolver de alguma forma.
> Já adianto que estou usando a qualidade da imagem na média e o zoom em 125% do navegador pois como é com números agora, as chances de dar problema são maiores.
> 
> A forma que estou fazendo vai ser para pegar os que tem 2 ou 3 energias, abaixo disso o bot se confunde

essa questão do zoom em 125% serve pra versão anterior ou essa q está trabalhando, pós atualização??

**Comment by walterdis** [comment]
> > Opa.
> > Já estou trabalhando para tentar resolver de alguma forma.
> > Já adianto que estou usando a qualidade da imagem na média e o zoom em 125% do navegador pois como é com números agora, as chances de dar problema são maiores.
> > A forma que estou fazendo vai ser para pegar os que tem 2 ou 3 energias, abaixo disso o bot se confunde
> 
> essa questão do zoom em 125% serve pra versão anterior ou essa q está trabalhando pós atualização??

Essa de agora ;)

**Comment by Acauan30** [comment]
testei agora com as configurações recomendadas e ele trava na seleção do boss, não clica no boss que está verde e fica dando como wait... pra sempre

**Comment by walterdis** [comment]
> testei agora com as configurações recomendadas e ele trava na seleção do boss, não clica no boss que está verde e fica dando como wait... pra sempre.
> 
> Edit: Até tirei print da minha tela para usar como referencia da imagem mas realmente não puxa para a luta, se eu clico manual o cod segue normal.

Estranho, essa parte não foi mexida.
Mexeu na qualidade e tudo o mais?

**Comment by Acauan30** [comment]
> > testei agora com as configurações recomendadas e ele trava na seleção do boss, não clica no boss que está verde e fica dando como wait... pra sempre.
> > Edit: Até tirei print da minha tela para usar como referencia da imagem mas realmente não puxa para a luta, se eu clico manual o cod segue normal.
> 
> Estranho, essa parte não foi mexida. Mexeu na qualidade e tudo o mais?

sim, mudei configuração, coloquei em todas, tirei print meu para usar como base, voltei ao padrão que estava. Nada funcionou, unica coisa que funcionou foi clicar manualmente. O restante do codigo está operando normalmente

**Comment by carauta3103** [comment]
valeu walter funcionou perfeito aqui, assim que fizer próximo saque mando uma doação pra você.

**Comment by walterdis** [comment]
> > > testei agora com as configurações recomendadas e ele trava na seleção do boss, não clica no boss que está verde e fica dando como wait... pra sempre.
> > > Edit: Até tirei print da minha tela para usar como referencia da imagem mas realmente não puxa para a luta, se eu clico manual o cod segue normal.
> > 
> > 
> > Estranho, essa parte não foi mexida. Mexeu na qualidade e tudo o mais?
> 
> sim, mudei configuração, coloquei em todas, tirei print meu para usar como base, voltei ao padrão que estava. Nada funcionou, unica coisa que funcionou foi clicar manualmente. O restante do codigo está operando normalmente

Pior que testei no Firefox, Chrome e Edge aqui, todos clicaram ali certinho no botão do boss.
Testa abrir o arquivo index.py na linha 143 (onde tem boss-fight-mode-icon)
Está com o valor 0.7 tenta modificar esse valor
Quanto mais alto, maior a precisão dele e quanto mais baixo menor (tenta diminuir um pouco pra ver 0.65 ou 0.6)

**Comment by walterdis** [comment]
> valeu walter funcionou perfeito aqui, assim que fizer próximo saque mando uma doação pra você.

Muito obrigado amigo ;)

**Comment by Saindramar** [comment]
> > > Opa.
> > > Já estou trabalhando para tentar resolver de alguma forma.
> > > Já adianto que estou usando a qualidade da imagem na média e o zoom em 125% do navegador pois como é com números agora, as chances de dar problema são maiores.
> > > A forma que estou fazendo vai ser para pegar os que tem 2 ou 3 energias, abaixo disso o bot se confunde
> > 
> > 
> > essa questão do zoom em 125% serve pra versão anterior ou essa q está trabalhando pós atualização??
> 
> Essa de agora ;)

Obrigado amigo, você é um amigo.

**Comment by Acauan30** [comment]
> 

troquei o navegador para um dos que voce testou porque antes eu estava usando no opera, mudei o cod da forma que tu falou e nada, o cursor do mouse nem mexe, fica piscando, no prompt.

> > > > testei agora com as configurações recomendadas e ele trava na seleção do boss, não clica no boss que está verde e fica dando como wait... pra sempre.
> > > > Edit: Até tirei print da minha tela para usar como referencia da imagem mas realmente não puxa para a luta, se eu clico manual o cod segue normal.
> > > 
> > > 
> > > Estranho, essa parte não foi mexida. Mexeu na qualidade e tudo o mais?
> > 
> > 
> > sim, mudei configuração, coloquei em todas, tirei print meu para usar como base, voltei ao padrão que estava. Nada funcionou, unica coisa que funcionou foi clicar manualmente. O restante do codigo está operando normalmente
> 
> Pior que testei no Firefox, Chrome e Edge aqui, todos clicaram ali certinho no botão do boss. Testa abrir o arquivo index.py na linha 143 (onde tem boss-fight-mode-icon) Está com o valor 0.7 tenta modificar esse valor Quanto mais alto, maior a precisão dele e quanto mais baixo menor (tenta diminuir um pouco pra ver 0.65 ou 0.6)

troquei o navegador para um dos que voce testou porque antes eu estava usando no opera, mudei o cod da forma que tu falou e nada, o cursor do mouse nem mexe, fica piscando, no prompt dando só wait T.T

**Comment by walterdis** [comment]
> ou



> > 
> 
> troquei o navegador para um dos que voce testou porque antes eu estava usando no opera, mudei o cod da forma que tu falou e nada, o cursor do mouse nem mexe, fica piscando, no prompt.
> 
> > > > > testei agora com as configurações recomendadas e ele trava na seleção do boss, não clica no boss que está verde e fica dando como wait... pra sempre.
> > > > > Edit: Até tirei print da minha tela para usar como referencia da imagem mas realmente não puxa para a luta, se eu clico manual o cod segue normal.
> > > > 
> > > > 
> > > > Estranho, essa parte não foi mexida. Mexeu na qualidade e tudo o mais?
> > > 
> > > 
> > > sim, mudei configuração, coloquei em todas, tirei print meu para usar como base, voltei ao padrão que estava. Nada funcionou, unica coisa que funcionou foi clicar manualmente. O restante do codigo está operando normalmente
> > 
> > 
> > Pior que testei no Firefox, Chrome e Edge aqui, todos clicaram ali certinho no botão do boss. Testa abrir o arquivo index.py na linha 143 (onde tem boss-fight-mode-icon) Está com o valor 0.7 tenta modificar esse valor Quanto mais alto, maior a precisão dele e quanto mais baixo menor (tenta diminuir um pouco pra ver 0.65 ou 0.6)
> 
> troquei o navegador para um dos que voce testou porque antes eu estava usando no opera, mudei o cod da forma que tu falou e nada, o cursor do mouse nem mexe, fica piscando, no prompt dando só wait T.T

No caso ele faz o login na metamask, tudo e apenas na seleção do boss que ele não está querendo selecionar?
Uma dúvida que podes ter respondido já mas se perdeu ali nos antigos.
Está configurado o jogo para inglês?

**Comment by Acauan30** [comment]
> > ou
> 
> > > 
> > 
> > 
> > troquei o navegador para um dos que voce testou porque antes eu estava usando no opera, mudei o cod da forma que tu falou e nada, o cursor do mouse nem mexe, fica piscando, no prompt.
> > > > > > testei agora com as configurações recomendadas e ele trava na seleção do boss, não clica no boss que está verde e fica dando como wait... pra sempre.
> > > > > > Edit: Até tirei print da minha tela para usar como referencia da imagem mas realmente não puxa para a luta, se eu clico manual o cod segue normal.
> > > > > 
> > > > > 
> > > > > Estranho, essa parte não foi mexida. Mexeu na qualidade e tudo o mais?
> > > > 
> > > > 
> > > > sim, mudei configuração, coloquei em todas, tirei print meu para usar como base, voltei ao padrão que estava. Nada funcionou, unica coisa que funcionou foi clicar manualmente. O restante do codigo está operando normalmente
> > > 
> > > 
> > > Pior que testei no Firefox, Chrome e Edge aqui, todos clicaram ali certinho no botão do boss. Testa abrir o arquivo index.py na linha 143 (onde tem boss-fight-mode-icon) Está com o valor 0.7 tenta modificar esse valor Quanto mais alto, maior a precisão dele e quanto mais baixo menor (tenta diminuir um pouco pra ver 0.65 ou 0.6)
> > 
> > 
> > troquei o navegador para um dos que voce testou porque antes eu estava usando no opera, mudei o cod da forma que tu falou e nada, o cursor do mouse nem mexe, fica piscando, no prompt dando só wait T.T
> 
> No caso ele faz o login na metamask, tudo e apenas na seleção do boss que ele não está querendo selecionar? Uma dúvida que podes ter respondido já mas se perdeu ali nos antigos. Está configurado o jogo para inglês?

Sim está em inglês. Antes da atualização eu já ativava o bot na tela principal, porque como uso o opera a metamask oculta o botão de aceitar, Antes de você colocar essa nova atualização só com os prints que os meninos colocaram aqui nesse post também estava rodando normal, foi eu baixar a nova versão do bot começou a travar na parte de seleção do bot.

**Comment by Acauan30** [comment]
> > 
> 
> > > > ou
> > > 
> > > 
> > > > > 
> > > > 
> > > > 
> > > > troquei o navegador para um dos que voce testou porque antes eu estava usando no opera, mudei o cod da forma que tu falou e nada, o cursor do mouse nem mexe, fica piscando, no prompt.
> > > > > > > > testei agora com as configurações recomendadas e ele trava na seleção do boss, não clica no boss que está verde e fica dando como wait... pra sempre.
> > > > > > > > Edit: Até tirei print da minha tela para usar como referencia da imagem mas realmente não puxa para a luta, se eu clico manual o cod segue normal.
> > > > > > > 
> > > > > > > 
> > > > > > > Estranho, essa parte não foi mexida. Mexeu na qualidade e tudo o mais?
> > > > > > 
> > > > > > 
> > > > > > sim, mudei configuração, coloquei em todas, tirei print meu para usar como base, voltei ao padrão que estava. Nada funcionou, unica coisa que funcionou foi clicar manualmente. O restante do codigo está operando normalmente
> > > > > 
> > > > > 
> > > > > Pior que testei no Firefox, Chrome e Edge aqui, todos clicaram ali certinho no botão do boss. Testa abrir o arquivo index.py na linha 143 (onde tem boss-fight-mode-icon) Está com o valor 0.7 tenta modificar esse valor Quanto mais alto, maior a precisão dele e quanto mais baixo menor (tenta diminuir um pouco pra ver 0.65 ou 0.6)
> > > > 
> > > > 
> > > > troquei o navegador para um dos que voce testou porque antes eu estava usando no opera, mudei o cod da forma que tu falou e nada, o cursor do mouse nem mexe, fica piscando, no prompt dando só wait T.T
> > > 
> > > 
> > > No caso ele faz o login na metamask, tudo e apenas na seleção do boss que ele não está querendo selecionar? Uma dúvida que podes ter respondido já mas se perdeu ali nos antigos. Está configurado o jogo para inglês?
> > 
> > 
> > Sim está em inglês. Antes da atualização eu já ativava o bot na tela principal, porque como uso o opera a metamask oculta o botão de aceitar, Antes de você colocar essa nova atualização só com os prints que os meninos colocaram aqui nesse post também estava rodando normal, foi eu baixar a nova versão do bot começou a travar na parte de seleção do bot.
> 
> O engraçado é que não mexi em nada no código nessa parte, apenas tirei um print novo com a qualidade no médio das imagens, então substituir elas era para resolver.
> 
> Fez uma cópia do antigo antes de baixar o novo certo?

tinha uma copia na lixeira, testei ele aqui, reconhece a janela do luna e pronto, wait pra sempre. Agora nem o antigo funciona

**Comment by Acauan30** [comment]
Eu percebi que no codigo assim que entra no boss hunt ele faz uma checagem de uma imagem "boss-hunt-map" mas quando eu jogo para 125% de zoom esse pedaço da tela fica encoberto, então talvez a falta de checar essa imagem esteja dando conflito

**Comment by hznandu** [comment]
Também estou com problemas, aparentemente o bot não seleciona o boss-hunt, acho essa resolução 125% bugou tudo.

**Comment by walterdis** [comment]
> Eu percebi que no codigo assim que entra no boss hunt ele faz uma checagem de uma imagem "boss-hunt-map" mas quando eu jogo para 125% de zoom esse pedaço da tela fica encoberto, então talvez a falta de checar essa imagem esteja dando conflito

Provavelmente é isso.

O que vocês podem fazer é diminuir o zoom e tirar novamente a foto das imagens para ver se corrige.
Eu fiz com 125% de zoom pois com 100% as imagens da energia ficam muito pequenas.

**Comment by hznandu** [comment]
Valeu pelo suporte Walter!

**Comment by walterdis** [comment]
> ser nerd é muito bom. Resolvi parte do problema, só o bot precisa de uma imagem para identificar que esta na tela do BOSS HUNT, eu tirei print daquelas caveiras que ficam no cenario, renomeei como "boss-hunt-map" e deu certo. Ele identificou que estava no cenario certo e foi pra frente. Mais facil do que ter que printar todas as figuras de novo. Mas quando zera a energia das bonecas a seta de voltar para BOSS HUNT também fica encoberta. Minha duvida é ficar nessa tela de seleção toma AFK ou não?

Boa =D
Acho que fica sim mas é pro bot apertar o botão de OK do afk
