### ISSUE TITLE
New update on lunarush broke the bot :(

### ISSUE THREAD

**Issue by machadox** [walterdis/lunarush-bot#37]
![image](https://user-images.githubusercontent.com/9204716/160915701-b6969c24-7716-4b20-a101-355915170477.png)
Hey, the game have a different "energy available" system (instead of showing 3 thunders, it uses now "x/3"

can you fix it? : X
Thx

**Comment by machadox** [comment]
![hero-list-depleted-energy](https://user-images.githubusercontent.com/9204716/160920329-8b297132-c8fc-44af-9ec1-4fc490a22b1f.png)
![hero-list-has-energy](https://user-images.githubusercontent.com/9204716/160920331-a33d5a39-3f56-4b9a-a55f-838b17b83a08.png)
![hero-select-depleted-energy](https://user-images.githubusercontent.com/9204716/160920332-0d3a3217-30ca-45b4-b8ec-454ad8984b09.png)
 ok replaced this 3 pictures and its working :)

**Comment by walterdis** [comment]
I've sent a new update.
Make sure you backup your current ;)
