### ISSUE TITLE
Mouse bug

### ISSUE THREAD

**Issue by druidou41** [walterdis/lunarush-bot#38]
I just downloaded your bot, but my mouse moves to the bottom right of my screen, I have a 4 screen configuration, do you have a solution?

**Comment by walterdis** [comment]
> I just downloaded your bot, but my mouse moves to the bottom right of my screen, I have a 4 screen configuration, do you have a solution?

In what screen?
Is your game in medium quality, 125% zoom in the browser?

**Comment by druidou41** [comment]
yes i have medium quality and 125% zoom
![bug](https://user-images.githubusercontent.com/16213916/160939867-bae160fe-daa0-42a1-8953-7f62a3cd6366.png)

**Comment by walterdis** [comment]
Try replacing the images.

**Comment by druidou41** [comment]
no, still the same problem, I tried to put it on another screen, my mouse always went down to the right.
anyway thank you for taking time for me

**Comment by walterdis** [comment]
Can u show me the console messages?

**Comment by druidou41** [comment]
![bug1](https://user-images.githubusercontent.com/16213916/160942317-74d37825-2230-41a0-a30e-ca5557a45093.png)

**Comment by druidou41** [comment]
I tried the command pip uninstall -r requirements.txt , then pip install -r requirements.txt
but I still have the same problem.

whereas before I had an old version of your BOT from the end of January, it worked perfectly.
weird :)
I'm going to sleep, I'll try again tomorrow

**Comment by walterdis** [comment]
> 

;(

> Author

;(
Try replacing this image or try to run the old bot to see if it happens again.


![boss-fight-mode-icon](https://user-images.githubusercontent.com/1938830/160945782-d4b34e69-2e53-428b-a9b8-d0052340bace.png)

**Comment by Soulbadguy54** [comment]
Hey Walter! Thx for update. Can you help me with the problem? I did different configurations already (125 %, medium quality), also tried to replace all images at boss level select stage. But bot do nothing, just wrote this:
Windows with "Luna Rush" text title found:  2
waiting ...
waiting ...
waiting ...
waiting ...
waiting ...
waiting ...
waiting ...
waiting ...

What should i try to do?

**Comment by Soulbadguy54** [comment]
ad how bot should understand has hero in select list energy or not? It checked only one image, but there is more states with energy (1/3, 2/3, 3/3).

**Comment by walterdis** [comment]
Hello, I submitted a new update to work again with 100% resolution in the browser.
Game quality: medium

Heroes with 1/3 energy will not be detected, only 2/3 and 3/3 because of image detection bug
