### ISSUE TITLE
Problema de resolução 

### ISSUE THREAD

**Issue by Flamesssssss** [walterdis/lunarush-bot#39]
O bot não funciona no notebook quando tento mudar a resolução para 125%, n tem como fazer o bot rodar na resolução 100%?

**Comment by walterdis** [comment]
> O bot não funciona no notebook quando tento mudar a resolução para 125%, n tem como fazer o bot rodar na resolução 100%?

Opa, é o zoom do navegador e não na resolução do sistema

**Comment by Flamesssssss** [comment]
Entendo perfeitamente, mas quando dou zoom no browser ate 125% fica mt grande e n da nem pra clicar na setinha do menu de voltar no luna

**Comment by walterdis** [comment]
> Entendo perfeitamente, mas quando dou zoom no browser ate 125% fica mt grande e n da nem pra clicar na setinha do menu de voltar no luna. N tem como o bot funcionar com 100% de resolução?

Mandei uma nova atualização, mudanças:
- Zoom do browser novamente para 100%
- Aumento de tempo de espera para 5000 segundos após rodar o bot (da para mudar na linha 89 do index.py)

Façam backup do anterior para caso de algum problema.

Obs: 1/3 de energia ainda não está pegando pois da problema no reconhecimento de imagem, apenas 2/3 e 3/3 estão funcionando corretamente.

**Comment by Flamesssssss** [comment]
E verdade o bot quando chega a 0/3 fica tentando atacar o boss eternamente....

**Comment by walterdis** [comment]
> 



> Aqui ele usou as 3 energias e quando chega a 0/3 fica tentando atacar o boss eternamente....

Tira os prints de novo

**Comment by Flamesssssss** [comment]
Vo tentar tirar meus prints, tem que ter algum cuidado com o tamanho?

**Comment by walterdis** [comment]
> Vo tentar tirar meus prints, tem que ter algum cuidado com o tamanho?

Podes usar os que tem de exemplo e testar novas possibilidades também

**Comment by Flamesssssss** [comment]
tentei aqui mas n vai kkk, n sei oque tem que fazer

**Comment by walterdis** [comment]
Da uma olhada aqui e veja se algo ajuda #47
