### ISSUE TITLE
Bot não seleciona as bonecas

### ISSUE THREAD

**Issue by Mauriciojrx** [walterdis/lunarush-bot#40]
Atualizei aqui, porém ele não seleciona nenhuma boneca, diz que não tem nenhuma com energia e vai pra tela de seleção de boss. Tentei add só as imagens novas e os códigos, mesma coisa.

**Comment by walterdis** [comment]
> Atualizei aqui, porém ele não seleciona nenhuma boneca, diz que não tem nenhuma com energia e vai pra tela de seleção de boss. Tentei add só as imagens novas e os códigos, mesma coisa.

Fez o que está descrito na documentação?
Qualidade média, zoom do navegador 125%, em inglês e etc?

**Comment by walterdis** [comment]
> > > Atualizei aqui, porém ele não seleciona nenhuma boneca, diz que não tem nenhuma com energia e vai pra tela de seleção de boss. Tentei add só as imagens novas e os códigos, mesma coisa.
> > 
> > 
> > Fez o que está descrito na documentação?
> > Qualidade média, zoom do navegador 125%, em inglês e etc?
> 
> Sim sim, só rodou em 100% na real (não entendi o porque), o restante já era a config que usava mesmo...

Estranho.
Se tiver alguma parte do jogo oculta quando vc der o zoom, pode dar problema mesmo no reconhecimento das imagens

**Comment by walterdis** [comment]
> > > > > Atualizei aqui, porém ele não seleciona nenhuma boneca, diz que não tem nenhuma com energia e vai pra tela de seleção de boss. Tentei add só as imagens novas e os códigos, mesma coisa.
> > > > 
> > > > 
> > > > Fez o que está descrito na documentação?
> > > > Qualidade média, zoom do navegador 125%, em inglês e etc?
> > > 
> > > 
> > > Sim sim, só rodou em 100% na real (não entendi o porque), o restante já era a config que usava mesmo...
> > 
> > 
> > Estranho.
> > Se tiver alguma parte do jogo oculta quando vc der o zoom, pode dar problema mesmo no reconhecimento das imagens
> 
> Pode ser isso então, se jogar no 125% a tela "come" parte do jogo, mas a barra de energia das bonecas fica normal, na teoria não era pra dar problema, né, ou mesmo assim dá?

Tentou substituir boa parte das imagens pelas novas? Principalmente as novas que adiconei 
- hero-select2x3-energy.png
- hero-select3x3-energy.png
- hero-selected-0x3-depleted-energy.png

Qualquer coisa, podes abrir o arquivo heroselect.py no metodo getHeroesInListWithenergyPositions() e onde tem positions2 = ... e positions3 = ..., vais ver que logo após o nome das imagens, tem um 0.95 e 0.93

Tenta ir diminuindo esses valores aos poucosp ra ver se resolve

**Comment by Mauriciojrx** [comment]
> > > > > > Atualizei aqui, porém ele não seleciona nenhuma boneca, diz que não tem nenhuma com energia e vai pra tela de seleção de boss. Tentei add só as imagens novas e os códigos, mesma coisa.
> > > > > 
> > > > > 
> > > > > Fez o que está descrito na documentação?
> > > > > Qualidade média, zoom do navegador 125%, em inglês e etc?
> > > > 
> > > > 
> > > > Sim sim, só rodou em 100% na real (não entendi o porque), o restante já era a config que usava mesmo...
> > > 
> > > 
> > > Estranho.
> > > Se tiver alguma parte do jogo oculta quando vc der o zoom, pode dar problema mesmo no reconhecimento das imagens
> > 
> > Pode ser isso então, se jogar no 125% a tela "come" parte do jogo, mas a barra de energia das bonecas fica normal, na teoria não era pra dar problema, né, ou mesmo assim dá?
> 
> Tentou substituir boa parte das imagens pelas novas? Principalmente as novas que adiconei 
> - hero-select2x3-energy.png
> - hero-select3x3-energy.png
> - hero-selected-0x3-depleted-energy.png
> 
> Qualquer coisa, podes abrir o arquivo heroselect.py no metodo getHeroesInListWithenergyPositions() e onde tem positions2 = ... e positions3 = ..., vais ver que logo após o nome das imagens, tem um 0.95 e 0.93
> 
> Tenta ir diminuindo esses valores aos poucosp ra ver se resolve

Tentei tbm, com essas imagens só adicionadas na pasta do bot, ele roda de boa até a parte da seleção, ai não consegue achar as que tem energia, se eu selecionar pra ele, ele repete certinho, mas para de novo quando zera. Vou tentar essa dica ai, valeu cara, muito obrigado

**Comment by Mauriciojrx** [comment]
> > > > > > Atualizei aqui, porém ele não seleciona nenhuma boneca, diz que não tem nenhuma com energia e vai pra tela de seleção de boss. Tentei add só as imagens novas e os códigos, mesma coisa.
> > > > > 
> > > > > 
> > > > > Fez o que está descrito na documentação?
> > > > > Qualidade média, zoom do navegador 125%, em inglês e etc?
> > > > 
> > > > 
> > > > Sim sim, só rodou em 100% na real (não entendi o porque), o restante já era a config que usava mesmo...
> > > 
> > > 
> > > Estranho.
> > > Se tiver alguma parte do jogo oculta quando vc der o zoom, pode dar problema mesmo no reconhecimento das imagens
> > 
> > 
> > Pode ser isso então, se jogar no 125% a tela "come" parte do jogo, mas a barra de energia das bonecas fica normal, na teoria não era pra dar problema, né, ou mesmo assim dá?
> 
> Tentou substituir boa parte das imagens pelas novas? Principalmente as novas que adiconei
> 
> * hero-select2x3-energy.png
> * hero-select3x3-energy.png
> * hero-selected-0x3-depleted-energy.png
> 
> Qualquer coisa, podes abrir o arquivo heroselect.py no metodo getHeroesInListWithenergyPositions() e onde tem positions2 = ... e positions3 = ..., vais ver que logo após o nome das imagens, tem um 0.95 e 0.93
> 
> Tenta ir diminuindo esses valores aos poucosp ra ver se resolve

Consegui aqui, fiz o seguinte, peguei o arquivo antigo, que estava rodando sem problemas e em zoom 100% e qualidade low, coloquei as imagens novas e substitui pelas que fiz com minha tela aberta no game, substitui os outros arquivos do python pelos do bot atualizado e fim, rodando liso de novo.

**Comment by walterdis** [comment]
Mandei uma nova atualização, mudanças:
- Zoom do browser novamente para 100%
- Aumento de tempo de espera para 5000 segundos após rodar o bot (da para mudar na linha 89 do index.py)

Façam backup do anterior para caso de algum problema.

Obs: 1/3 de energia ainda não está pegando pois da problema no reconhecimento de imagem, apenas 2/3 e 3/3 estão funcionando corretamente.
