### ISSUE TITLE
Tem como aumentar o tempo de espera do bot, por tipo 1h?

### ISSUE THREAD

**Issue by NaanDoH** [walterdis/lunarush-bot#41]
To achando de 12 a 17 min pouco, consigo altera essa configuração?

**Comment by walterdis** [comment]
Tem sim mas nessa versão eu já aumentei o tempo.
index.py na linha 89 tem waitTime = 5000 + uniform(20, 300)
podes modificar o 5000 ali para o tempo que vc quiser. (antes era 720 segundos)

**Comment by NaanDoH** [comment]
Ok, vou testar, muito obrigado!
