### ISSUE TITLE
nova versão 1.10.2 mudou as imagens

### ISSUE THREAD

**Issue by awmbaptista** [walterdis/lunarush-bot#42]
Mudou as imagens de energia, eu troquei para as que estão em anexo, mas em algum momento o bot não reconheceu apenas 3 heroínas quando ficaram com 1/3.
Vou mandar para vcs, mas talvez seja melhor esperar o dev.
![hero-select1x3-energy](https://user-images.githubusercontent.com/86299415/161031651-6024f6e2-f7fd-4228-906a-95b13b8eef0d.png)
![hero-select2x3-energy](https://user-images.githubusercontent.com/86299415/161031657-3c297ba7-89d1-4109-b746-09f45bcc89f6.png)
![hero-select3x3-energy](https://user-images.githubusercontent.com/86299415/161031658-00ce3234-7fe1-4404-8d1d-19cec252b89c.png)
![hero-selected-0x3-depleted-energy](https://user-images.githubusercontent.com/86299415/161031659-9bdca459-ab33-459a-8d74-b53210887d38.png)

**Comment by walterdis** [comment]
Eu fiz para não pegar os de 1/3 pois estava dando problema.
Teve uma atualização novamente agora a noite que ele deixa a energia apagada e vou usar essa imagem agora para detectar e imagino que vai solucionar os problemas ;)

**Comment by walterdis** [comment]
Acabei de enviar uma atualização nova que reverte o zoom para 100% novamente (só atualiza se não estiver funcionando direito)
Faz backup antes do seu script ;)

Ele continua botando as de 2 energia para cima apenas pois abaixo disso estava dando problema

**Comment by awmbaptista** [comment]
Como eu altero o heroselect.py para tentar buscar a energia 1/3 ?
Mesmo tirando o comentário das linhas 106 e 107 ele não vai. Estou tentando encontrar a imagem que funcione para ficar 100%!

**Comment by walterdis** [comment]
> Como eu altero o heroselect.py para tentar buscar a energia 1/3 ? Mesmo tirando o comentário das linhas 106 e 107 ele não vai. Estou tentando encontrar a imagem que funcione para ficar 100%!

Como eu disse, no momento não tem como fazer isso pois da problema direto.
Caso a boneca esteja lutando, ela vai lutar até acabar toda a energia dela, então a partir do momento que estiver em 2/3 ou 3/3, ela vai ser selecionada pra lutar até que gaste toda a energia ;)
