### ISSUE TITLE
LUNA VIP ENERGIA 5/5

### ISSUE THREAD

**Issue by Valtencirsa** [walterdis/lunarush-bot#44]
SERIA POSSIVEL AUMENTAR A QUANTIDADE DE ENERGIA PARA 5/5?

**Comment by walterdis** [comment]
> SERIA POSSIVEL AUMENTAR A QUANTIDADE DE ENERGIA PARA 5/5?

Podes tentar substituindo as imagens.
Eu não tenho VIP, então não tenho como desenvolver sem poder testar ;)

**Comment by Valtencirsa** [comment]
EU TENHO AS IMAGENS CASO QUEIRA, FIZ A ALTERAÇÃO MAS O BOT SÓ RECONHECE QUANDO ESTÁ 3/5 E 2/5
