### ISSUE TITLE
Falha na seleção de Hero

### ISSUE THREAD

**Issue by Acauan30** [walterdis/lunarush-bot#45]
Essa ultima versão que você postou não está fazendo a rolagem para selecionar as personagens. Por exemplo tem personagem com 2/3 ou até 3/3 no final da lista mas não está descendo então elas ficam ocultas e ele não busca por elas.

**Comment by walterdis** [comment]
Zoom: 100% ?
Qualidade do jogo: Média?
Idioma: Inglês?

Chegou a tirar os prints novamente? Para rolar ele precisa detectar a imagem com "warrior" escrito

**Comment by Acauan30** [comment]
> Zoom: 100% ? Qualidade do jogo: Média? Idioma: Inglês?
> 
> Chegou a tirar os prints novamente? Para rolar ele precisa detectar a imagem com "warrior" escrito

usando um print meu dessa imagem rodou normal agora
