### ISSUE TITLE
Bot clicks in the wrong places

### ISSUE THREAD

**Issue by SperFeckT** [walterdis/lunarush-bot#46]
![Screenshot_1](https://user-images.githubusercontent.com/54272882/161110077-b975b5d8-12ca-48b2-ba69-017627054b7b.png)
The screenshot shows that the bot cannot select the active boss, clicks to another part of the screen and waits

**Comment by walterdis** [comment]
Hi ;)
#47

**Comment by SperFeckT** [comment]
> Привет ;) Попробуйте здесь #47
![Screenshot_2](https://user-images.githubusercontent.com/54272882/161113420-2d69ec03-9a0a-4035-be17-a019cd180d22.png)
One more problem! Bot selects 2 heroes and clicks in empty screen(where mouse is)

**Comment by walterdis** [comment]
Sorry, didn't understand the problem.

Try to replace the images under target_images

**Comment by SperFeckT** [comment]
> Try to replace the images under target_images
I did it. So I gonna show you trajectory of mouse
![InkedScreenshot_2_LI](https://user-images.githubusercontent.com/54272882/161116573-28fff8a1-89f4-4088-affa-f08655ad6b59.jpg)

**Comment by walterdis** [comment]
Did you replaced boss-hunt-button.png too?

**Comment by SperFeckT** [comment]
> Did you replaced boss-hunt-button.png too?
Yes I'm sure

**Comment by walterdis** [comment]
Open heroselect.py
In the method def startFight():, replace `helper.clickDestinationImage('boss-hunt-button.png', 'boss-hunt')` to `helper.clickDestinationImage('boss-hunt-button.png', 'boss-hunt', 0.8)`

Try to increase 0.8 to 0.85 or 0.9 if still not working

**Comment by SperFeckT** [comment]
> Open heroselect.py In the method def startFight():, replace `helper.clickDestinationImage('boss-hunt-button.png', 'boss-hunt')` to `helper.clickDestinationImage('boss-hunt-button.png', 'boss-hunt', 0.8)`
> 
> Try to increase 0.8 to 0.85 or 0.9 if still not working
> 
> Is your browser zoom at 100% instead of 125%?

Hello again! I tried it so its still not working...
Yes my browser zoom is 100%

**Comment by walterdis** [comment]
What's showing at the console right after the wrong click?

**Comment by SperFeckT** [comment]
> What's showing at the console right after the wrong click?

waiting...

**Comment by walterdis** [comment]
screenshot please ;)
