### ISSUE TITLE
Ola Irei Corrigir e Implementar mudanças no bot em meu Repositório

### ISSUE THREAD

**Issue by ceiferking** [walterdis/lunarush-bot#50]
Farei mudanças e melhorias me baseando no seu script irei dar todos os créditos de criação e desenvolvimento inicial a você.
caso queira pode acompanhar minhas mudanças para ver se posso contribuir me algo para seu protejo.
meus fins são meramente académicos e uso pessoal.

**Comment by walterdis** [comment]
> Farei mudanças e melhorias me baseando no seu script irei dar todos os créditos de criação e desenvolvimento inicial a você. caso queira pode acompanhar minhas mudanças para ver se posso contribuir me algo para seu protejo. meus fins são meramente académicos e uso pessoal.

Opa cara.
Pode ficar a vontade, se tiver alguma dúvida ou algo do tipo é só dar um toque que eu ajudo no que puder ;)

**Comment by ceiferking** [comment]
Se puder dar uma olhada na ultima modificação que fiz no script de selecionar herois e passar feedback com energia agradeceria ^^

**Comment by walterdis** [comment]
Está funcionando ai certinho?

Quando fiz a primeira implementação eu botei para ele detectar o com 1/3 também, porém vi que as vezes ele detectava os 2/3 e 3/3 como se fossem o 1/3 e isso fazia com que o bot selecionasse e depois tirasse a seleção de alguns (por conta do parâmetro de threshold).

Por isso resolvi deixar pegando os de 2/3 para cima que dava menos problema.

Uma solução que seria a ideal, seria ele detectar pelo raio de energia no lado direito dos números mas, fazer com que a comparação levasse em conta a cor (o modo atual, ele transforma as imagens para preto e branco antes de comparar)

Não fui atrás para implementar dessa forma pois está atendendo minas necessidades.

Se estiver funcionando ai, deixa assim, mas como várias pessoas usam o bot, em cada pc ele pode se comportar de forma diferente 😁 

Ah, se você estiver estudando python para depois aplicar no profissional também, da uma pesquisada nos padrões de programação para python, o que eu usei (nome de métodos, variáveis e etc), eu usei as PSR do PHP (que é a linguagem principal de programação que eu uso)

https://peps.python.org/pep-0008/#method-names-and-instance-variables

**Comment by ceiferking** [comment]
vlw pela dica irei dar uma olhada no artigo.
esta forma que fiz funciona de que ele inicialmente eh pela logica tende a selecionar apenas 1/3 apos isso tende  selecionar 2/3 e depois 3/3 
na versao anterior que usava outra logica a forma q usei para detecção de energias era bem precisa ultilizada os padroes de imagem 1/3, 2/3, 3/3 com 1 pedação equivalente a o padrão numérico da imagem da parte cinza ao lado dos números isso fazia que quando a imagem escurecia ela não identificava o seleccionado como 1 fator de seleção pelo nível do cinza ao lado mudar muito com a sobreposição de cinza que eh adicionada ao seleccionar a personagem. 
esta eh a lógica de detecção mais precisa utilizando as imagem da interface atual.
pelo menos foi a conclusão que segui e funcionou e que vou aplicar nesta versão.
vou aprimorar a detecção para níveis gráficos muito inferiores aumentando a precisão na qualidade baixa e aumentando na qualidade alta pois segue padrões geométricos juntamente com de cor, funcionou perfeitamente  anteriormente, tentarei aplicar nesta versão atual do seu código.
