### ISSUE TITLE
Funcionando?

### ISSUE THREAD

**Issue by wsa7** [walterdis/lunarush-bot#53]
boa noite amigo, esta funcionando normalmente? tenho uma vps linux ubuntu aqui parada.. Apenas 1 conta mesmo..

**Comment by walterdis** [comment]
> boa noite amigo, esta funcionando normalmente? tenho uma vps linux ubuntu aqui parada.. Apenas 1 conta mesmo..

Estou usando até hoje.
No linux não funciona multi acct.
Vez ou outra ele tem problema em selecionar alguns bonecos e só seleciona com energia 2/3 e 3/3
Alguns problemas que podem ocorrer podes encontrar a solução aqui #47 ;)
