### ISSUE TITLE
bot stucks at level select

### ISSUE THREAD

**Issue by Soulbadguy54** [walterdis/lunarush-bot#54]
logs:

Windows with "Luna Rush" text title found:  2
Mode select found!!!
waiting ...
waiting ...
waiting ...
waiting ...
etc

I already changed all pictures but nothing helps, bot cant find what he should do after open the boss stage menu

**Comment by walterdis** [comment]
Did you tried everything described here? #47

**Comment by Soulbadguy54** [comment]
> Did you tried everything described here? #47 

Yeah, moreover in one window, bots do things right, in second window bots wrote: "complete stages not found". The settings pretty same, and i changed the image 5-6 times:/

**Comment by Soulbadguy54** [comment]
> Did you tried everything described here? #47 

And one more thing. In the instruction wrote: "bot dont select 1/3 energy heroes", but in my case bot do it.
Line of code corresponding to this are commented, accuracy set to 0.96, but it still happens...

**Comment by walterdis** [comment]
> > Did you tried everything described here? #47
> 
> And one more thing. In the instruction wrote: "bot dont select 1/3 energy heroes", but in my case bot do it. Line of code corresponding to this are commented, accuracy set to 0.96, but it still happens...

Accuracy is too high, try to lower a bit.
![image](https://user-images.githubusercontent.com/1938830/163167119-1df89eb7-7f7d-4c15-a8b7-76348071b2b7.png)



Make a backup and download the bot again to test
