### ISSUE TITLE
INTEGRAÇÃO COM TELEGRAM

### ISSUE THREAD

**Issue by 041gh0stt** [walterdis/lunarush-bot#56]
Seria super interessante uma interação no telegram, tipo o Bot manda print do saldo quando acabar a energia de todas as bonecas.

**Comment by walterdis** [comment]
Opa ;) 
A princípio não tenho intenção de fazer a implementação do telegram.
Se alguém fizer a implementação seguindo os padrões do bot, pode enviar um Pull Request que posso analisar e aceitar a implementação
