### ISSUE TITLE
Não está alternando para outras contas

### ISSUE THREAD

**Issue by legnatv** [walterdis/lunarush-bot#57]
Não está alternando para outras contas, como faço para usar a função multiaccount?

**Comment by walterdis** [comment]
Windows ou linux?
O multi account funciona apenas no windows e cada conta tem que estar em uma janela separada para que possa aparecer na barra de tarefas.

**Comment by legnatv** [comment]
> Windows ou linux? O multi account funciona apenas no windows e cada conta tem que estar em uma janela separada para que possa aparecer na barra de tarefas.

Windows, uso perfis diferentes em cada conta.

**Comment by walterdis** [comment]
E ele detecta as outras? (aparece no começo do uso do bot no console)
Está usando qual browser?

**Comment by legnatv** [comment]
Tá reconhecendo, só não alterna.
```
Windows with "Luna Rush" text title found:  4
Has Versus and Boss Icon Position:  True
Fight click  1
Has Versus and Boss Icon Position:  False
waiting ...
Hero select screen found!!!
selected heroes no energy:  0
Empty Slots:  0
```

**Comment by walterdis** [comment]
Ele só alterna a janela depois de jogar com todos os personagens de uma das contas e, não encontrar mais nenhum  com a energia cheia. É isso que está ocorrendo ai? (teve pessoas que acharam que ele ia alternando entre as janelas enquanto elas lutavam)

**Comment by legnatv** [comment]
> Ele só alterna a janela depois de jogar com todos os personagens de uma das contas e, não encontrar mais nenhum com a energia cheia. É isso que está ocorrendo ai? (teve pessoas que acharam que ele ia alternando entre as janelas enquanto elas lutavam)

ahh, pode ser isso, como eu to vindo de uma macro vip que alterna entre as contas e vai fazendo tudo ao mesmo tempo, eu achei que era assim tmb.
