### ISSUE TITLE
Não seleciona todas as lutadoras

### ISSUE THREAD

**Issue by denniszera** [walterdis/lunarush-bot#6]
boa tarde meu amigo, primeiramente obrigado pela iniciativa..
ele coloca as 3 primeiras, luta certinho e depois volta pro inicio do mapa e acaba nao rolando pra baixo pra colocar o restante.

"position to scroll heroes not found"

**Comment by walterdis** [comment]
> boa tarde meu amigo, primeiramente obrigado pela iniciativa.. ele coloca as 3 primeiras, luta certinho e depois volta pro inicio do mapa e acaba nao rolando pra baixo pra colocar o restante.
> 
> "position to scroll heroes not found"

Opa ;)
Coloca o jogo em inglês e a qualidade dele na minima.
Resolução de tela tem que estar em 1920x1080 também.

Se já tiver feito tudo isso, tenta pegar imagem hero-select-warrior-text.png e substituir por uma que você tirar igual por ai

**Comment by denniszera** [comment]
excelente meu amigo, foi resolvido colocando o jogo em qualidade minima, agradeço!!!
