### ISSUE TITLE
hangs out at choosing boss stage

### ISSUE THREAD

**Issue by Soulbadguy54** [walterdis/lunarush-bot#9]
subject. I changed some pictures, but bot still hangs out at this stage. Probably something changes after update today
logs:
Boss Icon Position:  0
Versus Icon Position:  0
waiting ...
Boss Icon Position:  0
Versus Icon Position:  0
waiting ...
Boss Icon Position:  0
Versus Icon Position:  0
waiting ...
Boss Icon Position:  0
Versus Icon Position:  0
waiting ...
Boss Icon Position:  0
Versus Icon Position:  0
waiting ...

**Comment by walterdis** [comment]
Hi ;)
Apparently it's stuck in the battle mode.
Have you tried to close and open the bot again?

**Comment by Soulbadguy54** [comment]
> Hi ;)
> Apparently it's stuck in the battle mode.
> Have you tried to close and open the bot again?
> 

Yes, of cause. I reload it, and every time it do like this as you said stuck at battle mode. What should i do to resolve this issue?

**Comment by walterdis** [comment]
I put both accounts I have to run at the same time on different computers. Both ran normally.

Can you confirm if:
- Your resolution is 1920x1080?
- Browser zoom is at 100%
- You game quality is at low (can change in config)
- Game is in english (rhetorical question but i have to) ;)

Try replacing:
- boss-hunt-map.png
- boss-hunt-button.png
- boss-fight-mode-icon.png
- connect-wallet.png

**Comment by Soulbadguy54** [comment]
> I put both accounts I have to run at the same time on different computers. Both ran normally.
> 
> Can you confirm if:
> 
> * Your resolution is 1920x1080?
> * Browser zoom is at 100%
> * You game quality is at low (can change in config)
> * Game is in english (rhetorical question but i have to) ;)
> 
> Try replacing:
> 
> * boss-hunt-map.png
> * boss-hunt-button.png
> * boss-fight-mode-icon.png
> * connect-wallet.png

thx. The change of game quality to low did the trick. But, there is new problem. After some hours when i return to the pc, i see the white screen and stucked bot. The machine got 8 gb RAM and good CPU. Can this problem can be connected with lack of ram? Or bot did something like reload a page and the program stucked?

**Comment by walterdis** [comment]
> > I put both accounts I have to run at the same time on different computers. Both ran normally.
> > Can you confirm if:
> > 
> > * Your resolution is 1920x1080?
> > * Browser zoom is at 100%
> > * You game quality is at low (can change in config)
> > * Game is in english (rhetorical question but i have to) ;)
> > 
> > Try replacing:
> > 
> > * boss-hunt-map.png
> > * boss-hunt-button.png
> > * boss-fight-mode-icon.png
> > * connect-wallet.png
> 
> thx. The change of game quality to low did the trick. But, there is new problem. After some hours when i return to the pc, i see the white screen and stucked bot. The machine got 8 gb RAM and good CPU. Can this problem can be connected with lack of ram? Or bot did something like reload a page and the program stucked?

Probably it's the game.
Even on my two computes with 16+ ram, after some hours, the game starts to slow down and i have to refresh de page
